name: "Clean untagged package versions."
description: "Action cleaning up untagged package versions published at ghcr.io."

inputs:
  package-name:
    description: "Package name."
    required: true
    type: string
  token:
    description: "Token with package deletion permissions."
    required: true
    type: string
  package-org:
    description: "Organization at which packages are published."
    required: false
    default: 'pyansys'
    type: string
  allow-last-days:
    description: "Avoid removing the last N days images: e.g. '2'."
    required: false
    default: ''
    type: string
  python-version:
    description: 'Desired Python version.'
    default: '3.10'
    required: false
    type: string

runs:
  using: "composite"
  steps:

    - name: "Set up Python ${{ inputs.python-version }}"
      uses: ansys/actions/_setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
        use-cache: false

    - name: "Install ghapi"
      shell: bash
      run: |

        python -m pip install --upgrade pip
        pip install ghapi

    - name: "Clone script"
      shell: bash
      run: |
        cat > clean-untagged.py << 'EOF'

        from datetime import datetime, timedelta
        import os

        from ghapi.all import GhApi
        from ghapi.core import print_summary
        from ghapi.page import paged

        PACKAGE_TIME_FORMAT = "%Y-%m-%dT%H:%M:%SZ"

        org_str = "${{ inputs.package-org }}"
        pck_str = "${{ inputs.package-name }}"
        last_days_str = "${{ inputs.allow-last-days }}"

        last_days = int(last_days_str) if last_days_str != "" else None
        if last_days:
            delete_before_date = datetime.now() - timedelta(days=last_days)

        api = GhApi(debug=print_summary, token=os.getenv("PACKAGE_DELETION_TOKEN"))

        paged_packages = paged(
            api.packages.get_all_package_versions_for_package_owned_by_org,
            org=org_str,
            package_name=pck_str,
            package_type="container",
            state="active",
            per_page=100,
        )

        # Loop over all pages
        for page in paged_packages:
            for package in page:
                # If keeping last days is requested, then check
                if (
                    last_days
                    and datetime.strptime(package.created_at, PACKAGE_TIME_FORMAT).timestamp()
                    > delete_before_date.timestamp()
                ):
                    continue

                # Check if the given package has no tags
                package_tags = package.metadata.container.tags

                # If no tags were found... delete it!
                if not package_tags:
                    print(f"Deleting package: {package}")
                    api.packages.delete_package_version_for_org(
                        org=org_str,
                        package_name=pck_str,
                        package_type="container",
                        package_version_id=package["id"],
                    )

        EOF
        cat clean-untagged.py

    - name: "Run package cleanup"
      shell: bash
      env:
        PACKAGE_DELETION_TOKEN: ${{ inputs.token }}
      run: |
        python clean-untagged.py

