# Copyright (C) 2022 - 2025 ANSYS, Inc. and/or its affiliates.
# SPDX-License-Identifier: MIT
#
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

name: |
  Documentation sitemap generator

description: |
  This process creates a ``sitemap.xml`` file, which enhances the search
  engine's browsing experience of our documentation. The process is a private
  composite action that is executed as a component of the PyAnsys documentation
  deployment strategies.

inputs:

  # Required inputs

  cname:
    description: |
      The canonical name (CNAME) containing the documentation.
    required: true
    type: string

  html-directory:
    description: |
      Name of the directory containing the HTML files of the website.
    required: true
    type: string


runs:
  using: "composite"
  steps:

    # ------------------------------------------------------------------------

    - uses: ansys/actions/_logging@v10.0.7
      with:
        level: "INFO"
        message: >
          Generating the XML sitemap.

    - name: "Generate the sitemap.xml file"
      shell: bash
      env:
        CNAME: ${{ inputs.cname }}
        HTML_DIRECTORY: ${{ inputs.html-directory }}
      run: |
        # Declare the website name and the output file for the sitemap
        website="https://${CNAME}"
        input_dir="${HTML_DIRECTORY}"
        output="sitemap.xml"

        # Add URLs to the sitemap
        echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" > $output
        echo "<urlset xmlns=\"http://www.sitemaps.org/schemas/sitemap/0.9\">" >> $output

        # Add homepage
        echo "  <url>" >> $output
        echo "    <loc>$website</loc>" >> $output
        echo "    <lastmod>$(date +%Y-%m-%dT%H:%M:%S+00:00)</lastmod>" >> $output
        echo "    <changefreq>daily</changefreq>" >> $output
        echo "    <priority>1.0</priority>" >> $output
        echo "  </url>" >> $output

        # Add other URLs
        while IFS= read -r -d '' file; do
          if [[ $file == *"$input_dir"* ]]; then
            url=${file}
          else
            # $input_dir is not in the file path, add it to the beginning of the URL
            url="$input_dir${file}"
          fi
          echo "  <url>" >> $output
          echo "    <loc>$website/$url</loc>" >> $output
          echo "    <lastmod>$(date +%Y-%m-%dT%H:%M:%S+00:00)</lastmod>" >> $output
          echo "    <changefreq>weekly</changefreq>" >> $output
          echo "    <priority>0.5</priority>" >> $output
          echo "  </url>" >> $output
        done < <(find "$input_dir" -type f -name "*.html" ! -name "search.html" ! -name "genindex.html" -print0)

        # Close the sitemap
        echo "</urlset>" >> $output
