# Copyright (C) 2022 - 2025 ANSYS, Inc. and/or its affiliates.
# SPDX-License-Identifier: MIT
#
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

name: "Set up Python"
description: "Set up Python and enables cache"

inputs:
  python-version:
    description: 'Desired Python version'
    required: true
    type: string
  use-cache:
    description: 'Whether to use Python/uv cache or not. Requires a pyproject.toml file.'
    required: true
    type: boolean
  provision-uv:
    description: 'Whether to provision uv alongside Python'
    required: true
    type: boolean
  prune-uv-cache:
    description: |
      Whether to prune uv cache or not. This input only has an effect if
      ``provision-uv`` is set to ``true``. If ``true``, the cache is pruned. If ``false``,
      the cache is not pruned. By default it is set to ``true``.

      .. note::

        When uv cache is pruned, pre-built wheels are removed but wheels built from source
        are retained.

    required: true
    type: boolean

runs:
  using: "composite"
  steps:

    - name: "Verify if python version is supported"
      id: python-version-support
      shell: bash
      env:
        PYTHON_VERSION: ${{ inputs.python-version }}
      run: |
        python_version="${PYTHON_VERSION}"
        minor_python_version=$(echo "$python_version" | awk -F "." '{print $2}')
        major_python_version=$(echo "$python_version" | awk -F "." '{print $1}')
        if (( $(( $major_python_version == 3 )) )) && (( $(( $minor_python_version < 9 )) )); then
          echo "python_version_supported=false" >> ${GITHUB_OUTPUT}
        elif (( $(( $major_python_version < 3 )) )); then
          echo "python_version_supported=false" >> ${GITHUB_OUTPUT}
        else
          echo "python_version_supported=true" >> ${GITHUB_OUTPUT}
        fi

    - uses: ansys/actions/_logging@main
      if: steps.python-version-support.outputs.python_version_supported == 'false'
      with:
        level: "ERROR"
        message: >
          Python version ${{ inputs.python-version }} is no longer supported. Please use a
          version greater than 3.8.

    # NOTE: When a workflow is triggered without using the cache, it can lead to a failure
    # in the Post Run action saying that the cache folder doesn't exist on disk.
    # This is related to our use of uv to install packages, see https://github.com/ansys/actions/pull/811
    - name: "Set up Python using cache"
      if: ${{ inputs.use-cache == 'true' && inputs.provision-uv == 'false'}}
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pip'
        cache-dependency-path: 'pyproject.toml'

    - name: "Set up Python without using cache"
      if: ${{ inputs.use-cache == 'false' || (inputs.use-cache == 'true' && inputs.provision-uv == 'true') }}
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
      with:
        python-version: ${{ inputs.python-version }}

    - name: "Set up uv"
      if: ${{ inputs.provision-uv == 'true' }}
      uses: astral-sh/setup-uv@f0ec1fc3b38f5e7cd731bb6ce540c5af426746bb # v6.1.0
      with:
        enable-cache: ${{ inputs.use-cache }}
        prune-cache: ${{ inputs.prune-uv-cache }}
