name: "Documentation deploy to specific repository."
description: "Deploy documentation to a specific documentation repository."

inputs:
  cname:
    description: 'The canonical name of the documentation website.'
    required: true
    type: string
  repository:
    description: "Repository for documentation deployment."
    required: true
    type: string
  bot-id:
    description: "Required application ID for documentation deployment."
    required: true
    type: string
  bot-token:
    description: "Required application token for documentation deployment."
    required: true
    type: string
  checkout:
      description: 'Whether to checkout the repository or not'
      default: true
      required: false
      type: boolean
  download-artifacts:
    description: 'Whether or not download the artifacts. By default download an artifact named "documentation-html"'
    required: false
    type: bool
    default: true


runs:
  using: "composite"
  steps:

    - name: "Checkout project in the GitHub Pages branch"
      uses: actions/checkout@v3
      if: ${{ inputs.checkout == 'true' }}

    - name: "Download the HTML documentation artifact"
      if: inputs.download-artifacts == 'true'
      uses: actions/download-artifact@v3
      with:
        name: documentation-html
        path: documentation-html

    - name: "Display structure of downloaded files"
      shell: bash
      run: |
        ls -R
  
    - name: "Include CNAME and nojekyll files expected by GitHub pages"
      shell: bash
      run: |
        touch documentation-html/CNAME documentation-html/.nojekyll
        echo ${{ inputs.cname }} > documentation-html/CNAME

    - name: "Get Bot Application Token"
      id: get-workflow-token
      uses: peter-murray/workflow-application-token-action@v2
      with:
        application_id: ${{ inputs.bot-id }}
        application_private_key: ${{ inputs.bot-token }}

    - name: "Deploy documentation"
      uses: JamesIves/github-pages-deploy-action@v4.4.0
      with:
        repository-name: ${{ inputs.repository }}
        token: ${{ steps.get-workflow-token.outputs.token }}
        branch: gh-pages
        folder: documentation-html
        clean: true
        clean-exclude: release
        single-commit: true 
