# Copyright (C) 2022 - 2026 ANSYS, Inc. and/or its affiliates.
# SPDX-License-Identifier: MIT
#
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

name: |
  Remove the documentation for a closed pull-request.

description: |
  This action removes the html documentation when the corresponding pull request is closed.
  By default, the ``gh-pages`` branch of the current repository is assumed, and the documentation
  is removed from ``https://<cname>/pull/<pr-number>/``.

inputs:

  # Required inputs
  cname:
    description: |
      The canonical name (CNAME) containing the documentation.
    required: true
    type: string

  token:
    description: |
      Required password, key or token with the correct credentials for deploying the
      documentation. If deploying to the current repository, the ``secrets.GITHUB_TOKEN`` token
      is enough. For workflows deploying to other repositories, `generate and
      use a token with write access
      <https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token>`_
      to that repository. ``contents: write`` and ``pull-requests: write`` are minimum permissions required for this token.
    required: true
    type: string

  bot-user:
    description: |
      Use the PYANSYS_CI_BOT_USERNAME as the user for a git commit & push.
    required: true
    type: string

  bot-email:
    description: |
      Use the PYANSYS_CI_BOT_EMAIL as the email for a git commit & push.
    required: true
    type: string

  # Optional inputs

  repository:
    description: |
      Repository name in the form of ``username/repository`` to be used for
      deploying the documentation. The current repository is assumed by default.
    required: false
    default: 'current'
    type: string

  branch:
    description: |
      Branch name for deploying the documentation. The ``gh-pages`` branch is
      used by default.
    required: false
    default: 'gh-pages'
    type: string

  commit-message:
    description: |
      Commit message used when deploying the documentation.
    required: false
    default: 'DOC: remove pull request documentation'
    type: string

  force-orphan:
    description: |
      Whether to force the deployment branch to be orphan or not. Default value
      is ``true``.
    required: false
    default: true
    type: string

runs:
  using: "composite"
  steps:

    - uses: ansys/actions/_logging@v10.2.4
      with:
        level: "WARNING"
        message: >
          Starting with version v10.2, the doc-deploy-pr action no longer requires you to add the "closed" GitHub event to "on.pull_request.types" for
          documentation cleanup when PRs are closed. Documentation for closed PRs is now cleaned up
          automatically in the background without requiring an explicit event trigger or additional configuration. For more details, see
          https://actions.docs.ansys.com/version/stable/migrations/docs-deploy-pr-setup.html
