name: "Build the wheelhouse of a Python library."
description: "Generate ZIP artifacts for the wheelhouse of a Python library."

inputs:
  library-name:
    description: 'Name of the Python library.'
    required: true
    type: string
  library-namespace:
    description: 'Namespace of the Python library.'
    required: true
    type: string
  operating-system:
    description: 'Name of the operating system.'
    required: true
    type: string
  python-version:
    description: 'Desired Python version for build.'
    required: true
    type: string
  use-python-cache:
    description: 'Whether to use Python cache or not. Requires a pyproject.toml file.'
    required: false
    default: true
    type: boolean
  target:
    description: 'Optional target to be passed for the build process.'
    required: false
    default: ''
    type: string
  checkout:
      description: 'Whether to checkout the repository or not.'
      default: true
      required: false
      type: boolean


runs:
  using: "composite"
  steps:

    - name: "Install Git and clone project"
      uses: actions/checkout@v3
      if: ${{ inputs.checkout == 'true' }}
  
    - name: "Set up Python ${{ inputs.python-version }}"
      uses: pyansys/actions/_setup-python@v3
      with:
        python-version: ${{ inputs.python-version }}
        use-cache: ${{ inputs.use-python-cache }}

    - name: "Update pip and install dependencies"
      shell: bash
      run: python -m pip install --upgrade pip build wheel

    - name: "Check if specific target is requested"
      shell: bash
      run: |
        echo "install_target=$( [[ '${{ inputs.target }}' == '' ]] && echo '.' || echo '.[${{ inputs.target }}]')" >> $GITHUB_ENV
        echo "wheelhouse_target=$( [[ '${{ inputs.target }}' == '' ]] && echo 'wheelhouse' || echo '${{ inputs.target }}-wheelhouse')" >> $GITHUB_ENV

    - name: "Install the library"
      shell: bash
      run: pip install ${{ env.install_target }}

    - name: "Verify library is properly installed and get its version number"
      shell: bash
      run: |
        echo "library_version=$(python -c "from ${{ inputs.library-namespace }} import __version__; print(__version__)")" >> $GITHUB_ENV

    - name: "Generate wheelhouse"
      shell: bash
      run: python -m pip wheel ${{ env.install_target }} -w wheelhouse

    - name: "Zip wheelhouse"
      uses: vimtor/action-zip@v1.1
      with:
        files: wheelhouse
        dest: ${{ inputs.library-name }}-v${{ env.library_version }}-${{ env.wheelhouse_target }}-${{ inputs.operating-system }}-${{ inputs.python-version }}.zip

    - name: "Upload wheelhouse"
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.library-name }}-v${{ env.library_version }}-${{ env.wheelhouse_target }}-${{ inputs.operating-system }}-${{ inputs.python-version }}
        path: '*.zip'
        retention-days: 7
