name: >
  Build wheelhouse action

description: >
  Generates compressed artifacts for the wheelhouse of a Python library. The
  wheelhouse contains all the necessary dependencies to install the project.
  This allows for local installations and avoids the need to connect to the
  online PyPI index.

inputs:

  # Required inputs

  library-name:
    description: >
      Name of the Python library. This is the name used when uploading the wheel
      and source distribution as artifacts. The name should be the same one used
      in the PyPI index.
    required: true
    type: string

  library-namespace:
    description: >
      Namespace of the Python library. The namespace is the path used when
      importing the library in Python. The library requires to have a
      ``__version__`` variable at its top ``__init__.py`` file.
    required: true
    type: string

  operating-system:
    description: >
      Name of the operating system where the library is installed.
    required: true
    type: string

  python-version:
    description: >
      Python version used for installing and running ``pre-commit``.
    required: true
    type: string

  # Optional inputs

  target:
    description: >
      Optional target used during the building process.
    required: false
    default: ''
    type: string

  use-python-cache:
    description: >
      Whether to use the Python cache for installing previously downloaded
      libraries. If ``true``, previously downloaded libraries are installed from the
      Python cache. If ``false``, libraries are downloaded from the PyPI index.
    required: false
    default: true
    type: boolean

runs:
  using: "composite"
  steps:

    - name: "Install Git and clone project"
      uses: actions/checkout@v3

    - name: "Set up Python ${{ inputs.python-version }}"
      uses: ansys/actions/_setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
        use-cache: ${{ inputs.use-python-cache }}

    - name: "Update pip and install the build and wheel libraries"
      shell: bash
      run: |
        python -m pip install --upgrade pip build wheel

    - name: "Check if specific target is requested"
      shell: bash
      run: |
        echo "install_target=$( [[ '${{ inputs.target }}' == '' ]] && echo '.' || echo '.[${{ inputs.target }}]')" >> $GITHUB_ENV
        echo "wheelhouse_target=$( [[ '${{ inputs.target }}' == '' ]] && echo 'wheelhouse' || echo '${{ inputs.target }}-wheelhouse')" >> $GITHUB_ENV

    - name: "Install the library"
      shell: bash
      run: |
        python -m pip install ${{ env.install_target }}

    - name: "Verify library is properly installed and get its version number"
      shell: bash
      run: |
        library_version=$(python -c "from ${{ inputs.library-namespace }} import __version__; print(); print(__version__)" | tail -1 || exit 1 )
        if [ -z "$library_version" ]; then
            echo "Problem getting the library version"
            exit 1;
        else
            echo "The library version is: $library_version";
        fi;
        echo "$library_version" >> $GITHUB_ENV

    - name: "Generate the wheelhouse"
      shell: bash
      run: |
        python -m pip wheel . -w wheelhouse

    - name: "Compress the wheelhouse"
      uses: vimtor/action-zip@v1.1
      with:
        files: wheelhouse
        dest: ${{ inputs.library-name }}-v${{ env.library_version }}-${{ env.wheelhouse_target }}-${{ inputs.operating-system }}-${{ inputs.python-version }}.zip

    - name: "Upload the compressed wheelhouse"
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.library-name }}-v${{ env.library_version }}-${{ env.wheelhouse_target }}-${{ inputs.operating-system }}-${{ inputs.python-version }}
        path: ${{ inputs.library-name }}-v${{ env.library_version }}-${{ env.wheelhouse_target }}-${{ inputs.operating-system }}-${{ inputs.python-version }}.zip
        retention-days: 7
