# Copyright (C) 2022 - 2025 ANSYS, Inc. and/or its affiliates.
# SPDX-License-Identifier: MIT
#
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

name: |
  Release to PyPI public index action

description: |
  Release library artifacts to the PyPI public index. Use the ``PYPI_TOKEN`` as
  the token. Artifacts get downloaded from the CI/CD pipeline and are assumed to be
  named ``<library-name>-artifacts``. This file is expected to contain a wheel file
  and a source distribution file for the desired library.

  .. attention::

      Starting with version ``ansys-actions@v9``, the ``use-trusted-publisher``
      input parameter is deprecated. Refer to the
      :ref:`release_pypi_trusted_publisher` if you wish to use this security
      feature.

inputs:

  # Required inputs

  library-name:
    description: |
      Name of the Python library to be published.
    required: true
    type: string

  # Optional inputs

  twine-username:
    description: |
      User name used when uploading to the public PyPI index.
    required: false
    default: '__token__'
    type: string

  twine-token:
    description: |
      Password used when uploading to the public PyPI index.
    required: false
    default: ''
    type: string

  use-trusted-publisher:
    description: |
      Whether to use the OIDC token for releasing. Default value is ``false``.
      This is useful when you want to publish to PyPI through a CI/CD pipeline
      as a Trusted Publisher. It is necessary that your repository has been authorized
      to use Trusted Publisher's. For more information, see
      `Using a Trusted Publisher <https://docs.pypi.org/trusted-publishers/>`_.

      .. note::

          ``permissions: id-token: write`` is mandatory for trusted publishing.


    required: false
    default: false
    type: boolean

  dry-run:
    description: |
      Whether to run or not this action in testing mode. Testing mode executes
      all the action steps except the releasing artifacts one. This allows
      developers to verify the health of the action once integrated in their
      CI/CD pipelines without actually publishing artifacts. Default value is
      ``false``.
    required: false
    default: false
    type: boolean

  skip-existing:
    description: |
      Continue uploading files if one already exists. Only valid when uploading
      to PyPI. Other implementations may not support this.
    required: false
    default: true
    type: boolean

  python-version:
    description: |
      Python version for installing and using `twine
      <https://twine.readthedocs.io/en/stable/>`_.
    required: false
    default: '3.11'
    type: string

runs:
  using: "composite"
  steps:

    - uses: ansys/actions/_logging@main
      with:
        level: "WARNING"
        message: >
          As the python ecosystem is moving to project metadata version 2.4,
          we need to use a more recent version of pypa/gh-action-pypi-publish.
          However, this action is not compatible with composite actions.
          Therefore, the `ansys/release-pypi-public` action is destined to
          disappear in a future version. We invite all users to define their
          release job manually. As an example, see
          https://actions.docs.ansys.com/version/stable/release-actions/index.html#release-pypi-template

    - name: "Release to the public PyPI index"
      uses: ansys/actions/_release-pypi@main
      with:
        library-name: ${{ inputs.library-name }}
        index-name: "https://upload.pypi.org/legacy/"
        twine-username: ${{ inputs.twine-username }}
        twine-token: ${{ inputs.twine-token }}
        python-version: ${{ inputs.python-version }}
        dry-run: ${{ inputs.dry-run }}
        skip-existing: ${{ inputs.skip-existing }}
        use-trusted-publisher: ${{ inputs.use-trusted-publisher }}
