# Copyright (C) 2022 - 2025 ANSYS, Inc. and/or its affiliates.
# SPDX-License-Identifier: MIT
#
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

name: |
  Documentation build action (Windows)

description: |
  Build library documentation using `Sphinx
  <https://www.sphinx-doc.org/en/master/>`_. The action installs documentation
  dependencies provided either in a requirement file, e.g.
  ``requirements/requirements_doc.txt``, or in the ``[doc]`` section of the
  additional dependencies in the ``pyproject.toml`` file. Assuming that
  `sphinx-build
  <https://www.sphinx-doc.org/en/master/man/sphinx-build.html>`_ is available
  after installing the documentation dependencies, the action uses it
  to generate documentation from the source. It requires that all the
  documentation is contained in the ``doc\`` directory of a project. The
  action locates the ``doc\make.bat`` and runs the ``make.bat html`` and
  ``make.bat pdf`` commands. If desired, the ``make.bat json`` command can
  also be executed to generate JSON documentation.

inputs:

  # Required inputs

  sphinxopts:
    description: |
      Set of options to pass to the ``Sphinx`` builder.

      .. note::

          This will override the ``SPHINXOPTS`` declared in your Makefile.

    required: true
    type: string

  dependencies:
    description: |
      String of system dependencies to be installed before building the
      documentation of the project.
    required: true
    type: string

  skip-dependencies-cache:
    description: |
      Whether to ignore dependencies cache or not for OS libraries.
    required: true
    type: boolean

  skip-install:
    description: |
      Whether to skip the installation of the project.
      Pure documentation projects require that this action be set to ``false``
      because there is no Python library associated with the project.
    required: true
    type: boolean

  requirements-file:
    description: |
      Path to the requirements file in case it needs to be in a specific location.
      This is useful for non python projects, where you don't necessarily have a requirements
      file in the root of the project.
    required: true
    type: string

  skip-json-build:
    description: |
      Whether to skip the generation of JSON documentation.
    required: true
    type: boolean

  check-links:
    description: |
      Whether to perform external link checks during the generation of
      documentation.
    required: true
    type: boolean

  add-pdf-html-docs-as-assets:
    description: |
      Whether to add PDF and HTML documentation as assets of the HTML
      documentation. The HTML documentation is compressed before being added.
      The PDF file name is expected to be retrieved through the documentation's
      configuration file 'conf.py' in 'doc\source'.

      .. warning::

          The HTML files are expected to be contained in ``doc\_build`` and the
          PDF file is copied in ``doc\_build\html\_static\assets\download``.
          If such directories do not exist in your repo, the action will fail.

    required: true
    type: boolean

  needs-quarto:
    description: |
      Whether to add a Quarto cheatsheet to the documentation. Default value is
      ``false``.

      .. warning::

        Quarto needs Jupyter to be installed. Make sure to add `Jupyter <https://pypi.org/project/jupyter/>` to
        the requirements list.
    required: true
    type: boolean

runs:
  using: "composite"
  steps:

    - uses: ansys/actions/_logging@main
      with:
        level: "INFO"
        message: >
          Install Chocolatey to install dependencies.

    - name: Download script and install Chocolatey
      shell: powershell
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force
        [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
        iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
        echo "C:\ProgramData\chocolatey\bin" | Out-File -Append -FilePath $env:GITHUB_PATH -Encoding utf8

    # ------------------------------------------------------------------------

    - uses: ansys/actions/_logging@main
      with:
        level: "INFO"
        message: >
          Install system dependencies. Even if no dependencies are provided,
          Miktex is installed to build the documentation.

    - name: Collect system dependencies
      shell: powershell
      run: |
        echo "NEEDED_DEPS=$(echo '${{ inputs.dependencies }}')" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    - name: Cache Chocolatey packages
      id: cache
      uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # v4.2.2
      if: ${{ (inputs.skip-dependencies-cache == 'false') && (env.NEEDED_DEPS != '') }}
      with:
        path: ~\AppData\Local\Temp\chocolatey
        key: choco-${{ env.NEEDED_DEPS }}
        restore-keys: choco

    - name: Install packages with Chocolatey
      if: ${{ (steps.cache.outputs.cache-hit != 'true') && (env.NEEDED_DEPS != '') }}
      shell: powershell
      run: choco install ${{ env.NEEDED_DEPS }} -y

    - name: Install Miktex and update PATH with Miktex binaries
      shell: powershell
      run: |
        choco install miktex -y
        echo "C:\Program Files\MiKTeX\miktex\bin\x64" | Out-File -Append -FilePath $env:GITHUB_PATH -Encoding utf8

    - name: "Install Poppler for PDF to PNG conversion"
      if: ${{ inputs.needs-quarto == 'true' }}
      shell: powershell
      run: |
        choco install poppler -y
        echo "C:\Program Files\poppler\bin" | Out-File -Append -FilePath $env:GITHUB_PATH -Encoding utf8

    - name: "Install quarto for cheatsheet"
      if: ${{ inputs.needs-quarto == 'true' }}
      shell: powershell
      run: |
        choco install quarto --version=1.6.43 -y
        echo "C:\ProgramData\chocolatey\lib\quarto\tools" | Out-File -Append -FilePath $env:GITHUB_PATH -Encoding utf8

    # ------------------------------------------------------------------------

    - uses: ansys/actions/_logging@main
      with:
        level: "INFO"
        message: >
          Set up Miktex to allow downloading missing packages when building documentation.

    - name: Set up Miktex to automatically install packages
      shell: powershell
      run: |
        initexmf --set-config-value [MPM]AutoInstall=1

    # ------------------------------------------------------------------------

    - name: Check Quarto Version
      if: ${{ inputs.needs-quarto == 'true' }}
      shell: powershell
      run: |
        quarto --version

    # ------------------------------------------------------------------------

    - uses: ansys/actions/_logging@main
      with:
        level: "INFO"
        message: >
          Determine context.

    - name: "Determine GitHub environment variables"
      shell: powershell
      run: |
        if ((Test-Path "pyproject.toml") -and (Get-Content "pyproject.toml" | Select-String -Pattern 'build-backend = "poetry\.core\.masonry\.api"')) {
          echo "BUILD_BACKEND=$(echo 'poetry')" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          echo "SPHINX_BUILD_MAKE=$(echo 'poetry run -- make.bat')" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        } else {
          echo "BUILD_BACKEND=$(echo 'pip')" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          echo "SPHINX_BUILD_MAKE=$(echo '.\make.bat')" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        }

    - uses: ansys/actions/_logging@main
      with:
        level: "INFO"
        message: >
          Build backend: ${{ env.BUILD_BACKEND }}
          Sphinx build make: ${{ env.SPHINX_BUILD_MAKE }}

    # ------------------------------------------------------------------------

    - uses: ansys/actions/_logging@main
      with:
        level: "INFO"
        message: >
          Set up python to build the documentation.

    # NOTE: Installation of poetry in a separate environment to the project to
    # avoid situations in which both poetry and the project have shared
    # dependencies with different version. This can lead to CICD failures. For
    # more information, see https://github.com/ansys/actions/pull/560
    - name: "Add pipx/bin directory to Github Path"
      if: env.BUILD_BACKEND == 'poetry'
      shell: powershell
      run: echo "${{ runner.temp }}/pipx/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    # NOTE: Poetry uses virtual environments when installing a project. As we
    # want to control that creation, we store POETRY_VIRTUALENVS_CREATE=false
    # in the GitHub environment.
    - name: "Set poetry environment variable(s)"
      if: env.BUILD_BACKEND == 'poetry'
      shell: powershell
      run: echo "POETRY_VIRTUALENVS_CREATE=$(echo false)" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    # NOTE: Install pipx in a location that can be used in following CICD jobs
    # but ensure that poetry is installed in a temporary folder cleaned before
    # and after each job. This way poetry is kinda "installed at system level"
    # making it available in the following call and installed in a different
    # environment from the project.
    - name: "Install poetry and create a virtual environment"
      if: env.BUILD_BACKEND == 'poetry'
      shell: powershell
      run: |
        python -m pip install pipx
        python -m pipx install poetry
        python -m venv .venv
      env:
        PIPX_BIN_DIR: ${{ runner.temp }}/pipx/bin
        PIPX_HOME : ${{ runner.temp }}/pipx/home

    - name: "Create a virtual environment"
      if: env.BUILD_BACKEND == 'pip'
      shell: powershell
      run: python -m venv .venv

    # ------------------------------------------------------------------------

    - name: "Update pip"
      shell: powershell
      run: |
        .venv\Scripts\Activate.ps1
        python -m pip install -U pip

    - name: "Check if requirements.txt file exists"
      shell: powershell
      run: |
        echo "EXISTS_DOC_REQUIREMENTS=$(if (Test-Path '${{ inputs.requirements-file }}') { echo 'true' } else { echo 'false' })" | Out-File -Append -FilePath $env:GITHUB_ENV -Encoding utf8

    - name: Install documentation dependencies from requirements file
      shell: powershell
      if: ${{ env.EXISTS_DOC_REQUIREMENTS == 'true' }}
      run: |
        .venv\Scripts\Activate.ps1
        python -m pip install -r ${{ inputs.requirements-file }}

    - name: Install Python library
      shell: powershell
      if: ${{ inputs.skip-install == 'false' }}
      run: |
        .venv\Scripts\Activate.ps1
        if ("${{ env.BUILD_BACKEND }}" -eq 'poetry' ) {
          poetry install
        } else {
          python -m pip install .
        }

    - name: Install documentation dependencies from pyproject.toml
      shell: powershell
      if: ${{ env.EXISTS_DOC_REQUIREMENTS == 'false' }}
      run: |
        .venv\Scripts\Activate.ps1
        if ("${{ env.BUILD_BACKEND }}" -eq 'poetry' ) {
          poetry install --with doc
        } else {
          python -m pip install .[doc]
        }

    # ------------------------------------------------------------------------

    - uses: ansys/actions/_logging@main
      with:
        level: "INFO"
        message: >
          Build HTML, PDF and JSON documentation.

    - name: Build HTML, PDF, and JSON documentation
      shell: powershell
      run: |
        .venv\Scripts\Activate.ps1
        cd doc
        ${{ env.SPHINX_BUILD_MAKE }} html SPHINXOPTS="${{ inputs.sphinxopts }}"
        ${{ env.SPHINX_BUILD_MAKE }} pdf
        if ("${{ inputs.check-links }}" -eq 'true' ) {
          ${{ env.SPHINX_BUILD_MAKE }} linkcheck SPHINXOPTS="${{ inputs.sphinxopts }}"
        }
        if ("${{ inputs.skip-json-build }}" -eq 'false' ) {
          ${{ env.SPHINX_BUILD_MAKE }} json SPHINXOPTS="${{ inputs.sphinxopts }}"
        }

    # ------------------------------------------------------------------------

    - uses: ansys/actions/_logging@main
      if: ${{ inputs.add-pdf-html-docs-as-assets == 'true' }}
      with:
        level: "INFO"
        message: >
          Set environment variable PDF_FILENAME.

    - name: Parse PDF file name
      if: ${{ inputs.add-pdf-html-docs-as-assets == 'true' }}
      shell: powershell
      run: |
        .venv\Scripts\Activate.ps1
        python ${{ github.action_path }}\..\python-utils\parse_doc_conf.py

    - uses: ansys/actions/_logging@main
      if: ${{ (inputs.add-pdf-html-docs-as-assets == 'true' ) && (env.PDF_FILENAME == '') }}
      with:
        level: "ERROR"
        message: >
          Unable to determine PDF filename using conf.py file.

    - uses: ansys/actions/_logging@main
      if: ${{ (inputs.add-pdf-html-docs-as-assets == 'true' ) && (env.PDF_FILENAME != '') }}
      with:
        level: "INFO"
        message: >
          Environment variable PDF_FILENAME set to ${{ env.PDF_FILENAME }}.

    # ------------------------------------------------------------------------

    - uses: ansys/actions/_logging@main
      with:
        level: "INFO"
        message: >
          Check if expected directories exist.

    - name: Set expected build directory
      shell: powershell
      run: |
        echo "EXPECTED_BUILD_DIR=$(echo 'doc\_build')" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    - name: Check expected build directory
      shell: powershell
      run: |
        echo "EXISTS_EXPECTED_BUILD_DIR=$(if (Test-Path '${{ env.EXPECTED_BUILD_DIR }}') { echo 'true' } else { echo 'false' })" | Out-File -Append -FilePath $env:GITHUB_ENV -Encoding utf8

    - uses: ansys/actions/_logging@main
      if: ${{ (inputs.add-pdf-html-docs-as-assets == 'true') && (env.EXISTS_EXPECTED_BUILD_DIR == 'false') }}
      with:
        level: "ERROR"
        message: >
          Expected build directory ${{ env.EXPECTED_BUILD_DIR }} does not exist.

    - name: Set expected download directory
      if: ${{ inputs.add-pdf-html-docs-as-assets == 'true' }}
      shell: powershell
      run: |
        echo "EXPECTED_DOWNLOAD_DIR=$(echo '${{ env.EXPECTED_BUILD_DIR }}\html\_static\assets\download')" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    - name: Check expected download directory
      if: ${{ inputs.add-pdf-html-docs-as-assets == 'true' }}
      shell: powershell
      run: |
        echo "EXISTS_EXPECTED_DOWNLOAD_DIR=$(if (Test-Path '${{ env.EXPECTED_DOWNLOAD_DIR }}') { echo 'true' } else { echo 'false' })" | Out-File -Append -FilePath $env:GITHUB_ENV -Encoding utf8

    - uses: ansys/actions/_logging@main
      if: ${{ (inputs.add-pdf-html-docs-as-assets == 'true') && (env.EXISTS_EXPECTED_DOWNLOAD_DIR == 'false') }}
      with:
        level: "WARNING"
        message: >
          Expected build directory ${{ env.EXPECTED_DOWNLOAD_DIR }} does not exist. Creating it...

    - name: Create expected download directory
      if: ${{ (inputs.add-pdf-html-docs-as-assets == 'true') && (env.EXISTS_EXPECTED_DOWNLOAD_DIR == 'false') }}
      shell: powershell
      run: |
        New-Item -ItemType directory ${{ env.EXPECTED_DOWNLOAD_DIR }}

    # ------------------------------------------------------------------------

    - name: Verify the docs have been generated properly
      if: ${{ env.EXISTS_EXPECTED_BUILD_DIR == 'true' }}
      shell: powershell
      run: |
        # Check if the HTML files have been generated
        if (Test-Path -Path "${{ env.EXPECTED_BUILD_DIR }}\html\index.html") {
          Write-Host "Docs have been generated successfully"
        } else {
          Write-Error "Docs have not been generated properly"
        }
        # Check if the PDF files have been generated
        if (Test-Path -Path "${{ env.EXPECTED_BUILD_DIR }}\latex\${{ env.PDF_FILENAME }}") {
          Write-Host "PDF has been generated successfully"
        } else {
          Write-Error "PDF has not been generated properly"
        }

    # ------------------------------------------------------------------------

    - name: Check build directory
      if: ${{ inputs.add-pdf-html-docs-as-assets == 'true' }}
      uses: ansys/actions/_logging@main
      with:
        level: "INFO"
        message: >
          Add PDF and HTML documentation as assets.

    - name: Add assets to HTML docs
      if: ${{ inputs.add-pdf-html-docs-as-assets == 'true' }}
      shell: powershell
      run: |
        cd ${{ env.EXPECTED_BUILD_DIR }}\html; zip -r documentation-html.zip *; cd ..\..\..
        mv ${{ env.EXPECTED_BUILD_DIR }}\html\documentation-html.zip ${{ env.EXPECTED_DOWNLOAD_DIR }}
        if (Test-Path ${{ env.EXPECTED_BUILD_DIR }}\latex\${{ env.PDF_FILENAME }}) {
          cp ${{ env.EXPECTED_BUILD_DIR }}\latex\${{ env.PDF_FILENAME }} ${{ env.EXPECTED_DOWNLOAD_DIR }}
          Write-Output "File ${{ env.EXPECTED_BUILD_DIR }}\latex\${{ env.PDF_FILENAME }} has been copied."
        } else {
          cp ${{ env.EXPECTED_BUILD_DIR }}\latex\*.pdf ${{ env.EXPECTED_DOWNLOAD_DIR }}
          Write-Output "Couldn't find ${{ env.EXPECTED_BUILD_DIR }}\latex\${{ env.PDF_FILENAME }}, every existing PDF file has been copied."
        }

    # ------------------------------------------------------------------------

    - uses: ansys/actions/_logging@main
      with:
        level: "INFO"
        message: >
          Upload HTML, PDF and JSON documentation.

    - name: Upload HTML documentation artifact
      uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
      with:
        name: documentation-html
        path: doc/_build/html
        retention-days: 7

    - name: Upload PDF documentation artifact
      uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
      with:
        name: documentation-pdf
        path: doc/_build/latex/*.pdf
        retention-days: 7

    - name: Upload JSON documentation artifact
      uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
      if: inputs.skip-json-build == 'false'
      with:
        name: documentation-json
        path: doc/_build/json
        retention-days: 7
