name: >
  Documentation style

description: >
    Check documentation style using `Vale <https://vale.sh/>`_. This action is a
    wrapper on top of the `errata-ai/vale-action
    <https://github.com/errata-ai/vale-action>`_.

inputs:

  # Required inputs

  token:
    description: >
      The token value used to authorize Vale to add comments and suggestions in
      the file section.
    required: true
    type: string

  # Optional inputs

  vale-config:
    description: >
      Path to the Vale configuration file.
    default: 'doc/.vale.ini'
    required: false
    type: string

  vale-version:
    description: >
      Version number for Vale.
    default: '3.3.0'
    required: false
    type: string

  checkout:
      description: >
        Whether to clone the repository in the CI/CD machine. Default value is
        ``true``.
      default: true
      required: false
      type: boolean

runs:
  using: "composite"
  steps:

    - name: "Install Git and clone project"
      uses: actions/checkout@v4
      if: inputs.checkout == 'true'

    # TODO: remove this deprecation in ansys/actions@v6

    - name: "Build deprecation warning"
      if: startswith(inputs.vale-version, '2.')
      shell: bash
      run: |
        deprecation_text="
        Ansys Actions v6 will include by default Vale version v3. For
        migrating, please update your 'doc/.vale.ini' file and 'doc/styles'
        directory as in this pull-request https://github.com/ansys/pymechanical/pull/613
        "
        echo "DEPRECATION_TEXT=$(echo $deprecation_text)" >> $GITHUB_ENV

    - uses: ansys/actions/_logging@main
      if: startswith(inputs.vale-version, '2.')
      with:
        level: "WARNING"
        message: >
          Ansys Actions v6 will include by default Vale version v3. For
          migrating, please update your "doc/.vale.ini" file and "doc/styles"
          directory as in this pull-request https://github.com/ansys/pymechanical/pull/613

    - name: "Raise deprecation warning outside of the CI/CD logs"
      shell: bash
      if: startswith(inputs.vale-version, '2.')
      run: |
        echo "::warning ::${DEPRECATION_TEXT}"

    # TODO: end

    - name: "Run Vale"
      uses: errata-ai/vale-action@reviewdog
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      with:
        files: doc
        reporter: github-pr-check
        level: error
        filter_mode: nofilter
        fail_on_error: true
        vale_flags: "--config=${{ inputs.vale-config }}"
        version: ${{ inputs.vale-version }}
