name: "Documentation style."
description: "Check documentation style using Vale."

inputs:
  vale-config:
    description: "Path to the Vale configuration file."
    default: "doc/.vale.ini"
    required: false
    type: string
  token:
    description: "Required token for Vale commenter."
    required: true
    type: string
  checkout:
      description: 'Whether to checkout the repository or not'
      default: true
      required: false
      type: boolean

runs:
  using: "composite"
  steps:

    - name: "Install Git and clone project"
      uses: actions/checkout@v3
      if: ${{ inputs.checkout == 'true' }}

    - name: "Run Vale"
      uses: errata-ai/vale-action@reviewdog
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      with:
        files: doc
        reporter: github-pr-check
        level: error
        filter_mode: nofilter
        fail_on_error: true
        vale_flags: "--config=${{ inputs.vale-config }}"
