name: >
  Documentation style

description: >
    Check documentation style using `Vale <https://vale.sh/>`_. This action is a
    wrapper on top of the `errata-ai/vale-action
    <https://github.com/errata-ai/vale-action>`_.

inputs:
  token:
    description: >
      The token value used to authorize Vale to add comments and suggestions in
      the file section.
    required: true
    type: string
  vale-config:
    description: >
      Path to the Vale configuration file.
    default: "doc/.vale.ini"
    required: false
    type: string
  checkout:
      description: >
        If ``true``, clones the repository in the CI/CD machine. Use ``false``
        when not using this action as complete job need to.
      default: true
      required: false
      type: boolean

runs:
  using: "composite"
  steps:

    - name: "Install Git and clone project"
      uses: actions/checkout@v3
      if: ${{ inputs.checkout == 'true' }}

    - name: "Run Vale"
      uses: errata-ai/vale-action@reviewdog
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      with:
        files: doc
        reporter: github-pr-check
        level: error
        filter_mode: nofilter
        fail_on_error: true
        vale_flags: "--config=${{ inputs.vale-config }}"
