# This file is required by the the action 'https://github.com/actions/labeler'
# and used in the '.github/workflows/ci_cd_pr.yml' workflow

# -- Labels based on PR title ------------------------------------------------
'fix':
  - head-branch: ['fix']

'enhancement':
  - head-branch: ['feat']

# -- Documentation labels ----------------------------------------------------
'docs':
  - all:
      - changed-files:
          - any-glob-to-any-file: ['README.md', 'doc/source/**/*.rst']
          - all-globs-to-all-files: ['!doc/styles/**', '!doc/.vale.ini']

## -- Other labels ------------------------------------------------------------
'code-style':
  - any:
      - changed-files:
          - any-glob-to-any-file: ['.pre-commit-config.yaml', 'doc/.vale.ini']

'ci':
  - any:
      - changed-files:
          - any-glob-to-any-file: ['.github/workflows/**']

'tests':
  - any:
      - changed-files:
          - any-glob-to-any-file: ['tests/**']
