# This file is required by the the action 'https://github.com/actions/labeler'
# and used in the '.github/workflows/ci_cd_pr.yml' workflow

# -- Labels based on PR title ------------------------------------------------
'fix':
  - head-branch: ['fix']

'enhancement':
  - head-branch: ['feat']

# -- Documentation labels ----------------------------------------------------
'docs':
  - all:
      - changed-files:
          - any-glob-to-any-file: ['README.md', 'doc/source/**/*.rst']
          - all-globs-to-all-files: ['!doc/styles/**', '!doc/.vale.ini']

## -- Other labels ------------------------------------------------------------
'style':
  - any:
      - changed-files:
          - any-glob-to-any-file: ['.pre-commit-config.yaml', 'doc/.vale.ini']

'ci':
  - any:
      - changed-files:
          - any-glob-to-any-file: ['.github/workflows/**']

'tests':
  - any:
      - changed-files:
          - any-glob-to-any-file: ['tests/**']

# HACK: the following labels are declared with the only purpose of avoiding the
# GitHub labeler bot to remove those. This is a known issue reported in the
# official action/labeler repo https://github.com/actions/labeler/issues/763

'deploy-pr-doc':
  - all:
      - changed-files:
          - all-globs-to-all-files: ['THIS-NEVER-MATCHES-A-FILE']
