repos:

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: 77039ccbba72c8aede339c5f8ae29b42aced0a2e  # frozen: v0.15.18
  hooks:
    - id: ruff-check
    - id: ruff-format

- repo: https://github.com/adamchainz/blacken-docs
  rev: fda77690955e9b63c6687d8806bafd56a526e45f  # frozen: 1.20.0
  hooks:
    - id: blacken-docs
      additional_dependencies: [black==26.5.1]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
  hooks:
  - id: check-merge-conflict
  - id: check-yaml
  - id: requirements-txt-fixer
  - id: trailing-whitespace
  - id: debug-statements

# Validate our github workflow files
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 5030dca3047414c338091455ac41803200ec1f0f  # frozen: 0.37.3
  hooks:
    - id: check-github-workflows

- repo: https://github.com/ansys/pre-commit-hooks
  rev: 55c5b6a5439abd847613579c6924da750e8b78b2  # frozen: v0.8.0
  hooks:
    - id: add-license-headers
      files: '/.*\.(yml|py)$'
      args:
      - --start_year=2022
      exclude: '^(.github|doc)/.*'