repos:

- repo: https://github.com/psf/black
  rev: 87928e6d6761a4a6d22250e1fee5601b3998086e  # frozen: 26.5.1
  hooks:
  - id: black

- repo: https://github.com/pycqa/isort
  rev: dac090ce4d9ee313d086e2e89ab1acb8c2664fa1  # frozen: 9.0.0a3
  hooks:
  - id: isort
    args: ["--line-length", "88", "--profile", "black"]

- repo: https://github.com/PyCQA/flake8
  rev: d93590f5be797aabb60e3b09f2f52dddb02f349f  # frozen: 7.3.0
  hooks:
  - id: flake8

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
  hooks:
  - id: check-merge-conflict
  - id: check-yaml
  - id: requirements-txt-fixer
  - id: trailing-whitespace
  - id: debug-statements

# Validate our github workflow files
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 943377262562a12b57292fc98fabd7dbf81451fe  # frozen: 0.37.2
  hooks:
    - id: check-github-workflows

- repo: https://github.com/ansys/pre-commit-hooks
  rev: ad4e7598809ad98cde5aaf52d80040c7ac56e7cf  # frozen: v0.7.2
  hooks:
    - id: add-license-headers
      files: '/.*\.(yml|py)$'
      args:
      - --start_year=2022
      exclude: '^(.github|doc)/.*'