name: >
  Lint Dockerfile

description: >
  Evaluate the quality of your project Dockerfile(s) by using `hadolint
  <https://github.com/hadolint/hadolint/>`_. This action is expected to be used within a
  matrix job to lint Dockerfile(s) from multiple directories. The action uses `hadolint-action
  <https://github.com/hadolint/hadolint-action>`_ behind the scenes. If you want to evaluate multiple
  Dockerfiles contained in various directories of the provided directory, use the recursive option.

  This action emphasis the fact of having Dockerfile(s) contained inside the "docker" directory in the
  root of the project. Exception can be added as it is the case for the ".devcontainer" directory.

  .. warning::
      Two checks are performed and failing any of them results in the action failure:
      - the root of the project must contain a docker directory;
      - the provided directory must be allowed, i.e. is either "docker" or ".devcontainer".

inputs:

  # Required inputs

  directory:
    description: >
      Directory from which to search for Dockerfile(s).
    required: true

  # Optional inputs

  recursive:
    description: >
      Search for Dockerfile(s) recursively.
    required: false
    default: false

  error-level:
    description: >
      Fail action based on hadolint output (-1: never, 0: error, 1: warning, 2: info)
    required: false
    default: 2

runs:
  using: "composite"
  steps:

    - name: Check docker directory existence
      shell: bash
      run: |
        if [ ! -d "${{ github.workspace }}/docker" ]; then
          echo "Directory 'docker' does not exist. Except in special cases, e.g. '.devcontainer', we emphasize that dockerfiles are expected to be in the docker directory in the root of the project."
          exit 1
        fi

    # Changes performed in allowed_working_dirs should be applied to the code-style action.
    - name: Check provided directory
      shell: bash
      run: |
        allowed_working_dirs=("docker" ".devcontainer")
        is_allowed=false
        for dir in "${allowed_working_dirs[@]}"
        do
          if [ "$dir" == "${{ inputs.directory }}" ] ; then
            is_allowed=true
          fi
        done
        if [ "$is_allowed" == true ] ; then
          echo "Provided directory '${{ inputs.directory }}' is allowed"
        else
          echo "Provided directory '${{ inputs.directory }}' is not allowed"
          exit 1
        fi

    # - name: Install hadolint
    #   shell: bash
    #   run: |
    #     brew install hadolint

    # - name: Run Hadolint
    #   working-directory: ${{ inputs.directory }}
    #   shell: bash
    #   run: |
    #     hadolint Dockerfile
    # Workaround used because option "work-directory" cannot be used with "uses", it only works with the key-word "run".
    - name: Move to specific directory
      shell: bash
      run: |
        cd ${{ github.workspace }}/${{ inputs.directory }}

    - name: Run Hadolint
      uses: jbergstroem/hadolint-gh-action@v1
      # env:
      #   HADOLINT_RECURSIVE: "${{ inputs.recursive }}"
      with:
        dockerfile: "${{ inputs.directory }}/**/Dockerfile"
        # recursive: ${{ inputs.recursive }}
        error_level: ${{ inputs.error-level }}
