name: "Check licenses"
description: "Check if package licenses in the current environment are among the accepted ones"

inputs:
  accepted-licenses:
    description: "List of accepted licenses"
    default: "MIT BSD Apache PSF HPND"
    required: false
    type: string

runs:
  using: "composite"
  steps:

    - name: "Check licences of packages"
      shell: bash
      run: |
        echo ${{ inputs.accepted-licenses }}
        python -m pip install matplotlib numpy
        python -m pip install pip-licenses
        input=("MIT" "BSD" "Apache" "PSF" "HPND")
        accepted_licenses=''
        for license in ${input[*]}; do accepted_licenses+="$license\|"; done
        accepted_licenses=${accepted_licenses::-2}
        pip-licenses
        pip-licenses --summary
        pip-licenses --summary --ignore-packages matplotlib | grep -v $accepted_licenses
        pip uninstall -y pip-licenses