name: "Check licenses"
description: "Check if package licenses in the current environment are among the accepted ones"

inputs:
  accepted-licenses:
    description: "List of accepted licenses"
    default: "MIT BSD Apache PSF HPND"
    required: false
    type: string

runs:
  using: "composite"
  steps:

    - name: "Check licences of packages"
      shell: bash
      run: |
        echo ${{ inputs.accepted-licenses }}
        python -m pip install matplotlib numpy
        python -m pip install pip-licenses
        mapfile licenses_from_txt < check-licenses/accepted-licenses.txt
        echo "Accept licences if they contain:"
        accepted_licenses=''
        for license in ${licenses_from_txt[*]}; do echo $license && accepted_licenses+="$license\|"; done
        accepted_licenses=${accepted_licenses::-2}
        echo $accepted_licenses
        pip-licenses
        pip-licenses --summary
        if [[ -z $(pip-licenses --summary --ignore-packages matplotlib | grep -v $accepted_licenses | tail -n+2) ]]; then
          echo "All licenses are valid"
        else
          echo "Invalid licenses found. Failing action."
          exit
        fi
        pip uninstall -y pip-licenses