name: "Check licenses"
description: "Check if package licenses in the current environment are among the accepted ones"

inputs:
  accepted-licenses:
    description: "List of accepted licenses"
    default: "MIT BSD Apache PSF HPND"
    required: false
    type: string

runs:
  using: "composite"
  steps:

    - name: "Check licences of packages"
      shell: bash
      run: |
        python -m pip install matplotlib numpy
        python -m pip install pip-licenses
        mapfile licenses_from_txt < check-licenses/accepted-licenses.txt
        echo "Accept licences if they contain:"
        accepted_licenses=''
        for license in ${licenses_from_txt[*]}; do echo $license && accepted_licenses+="$license\|"; done
        accepted_licenses=${accepted_licenses::-2}
        mapfile ignored_packages_from_txt < check-licenses/ignored-packages.txt
        echo "Ignored (trusted) packages are:"
        ignored_packages=''
        for pckg in ${ignored_packages_from_txt[*]}; do echo $pckg && ignored_packages+="$pckg "; done
        ignored_packages_from_txt=${ignored_packages_from_txt::-1}
        if [[ -z $(pip-licenses --summary --ignore-packages $ignored_packages | grep -v $accepted_licenses | tail -n+2) ]]; then
          echo "All licenses are valid"
        else
          echo "Failing action: Invalid licenses found. The invalid licenses and its associated packages are:"
          pip-licenses --ignore-packages $ignored_packages | grep -v $accepted_licenses
          exit 1
        fi
        pip uninstall -y pip-licenses