name: "Check licenses"
description: "Check if package licenses in the current environment are among the accepted ones"

inputs:
  accepted-licenses:
    description: "List of accepted licenses"
    default: "MIT"
    required: false
    type: string

runs:
  using: "composite"
  steps:

    - name: "Check licences of packages"
      shell: bash
      run: |
        pip install pip-licenses
        licenses=$(pip-licenses --summary)
        echo This is licences before entering to py script
        echo $licenses
        python check-licenses/check_licenses.py -l=$licenses
        pip uninstall -y pip-licenses