name: "Check licenses"
description: "Check if package licenses in the current environment are among the accepted ones"

inputs:
  accepted-licenses:
    description: "List of accepted licenses"
    default: "MIT"
    required: false
    type: string

runs:
  using: "composite"
  steps:

    - name: "Check licences of packages"
      shell: bash
      run: |
        pip install pip-licenses
        input=('MIT' 'BSD' 'Apache' 'PSF' 'HPND')
        accepted_licenses=''
        for license in ${input[*]}; do accepted_licenses+="$license\|"; done
        echo $accepted_licenses
        accepted_licenses=${accepted_licenses::-2}
        echo $accepted_licenses
        echo pip-licenses
        pip-licenses
        echo "pip-licenses --summary"
        pip-licenses --summary
        echo $(pip-licenses --summary)
        echo "$(pip-licenses --summary)"
        echo "$(pip-licenses --summary | grep -v $accepted_licenses)"
        pip-licenses --summary | grep -v $accepted_licenses
        pip uninstall -y pip-licenses