name: "Check licenses"
description: "Check if package licenses in the current environment are among the accepted ones"

inputs:
  accepted-licenses:
    description: "List of accepted licenses"
    default: "MIT"
    required: false
    type: string

runs:
  using: "composite"
  steps:
    - name: "List all the content of current directory"
      shell: bash
      run: ls

    - name: "Check licences of packages"
      shell: bash
      run: |
        pip install pip-licenses
        echo "LICENSES=$(echo 'pip-licenses --summary')" >> $GITHUB_ENV
        echo ${{ env.LICENSES }}
        python check-licenses/check_licenses.py
        pip uninstall -y pip-licenses