name: >
  Commit style

description: >
  Action that checks if the title of the pull request is following the
  conventional commits standard.

inputs:

  # Required inputs

  token:
    description: >
      The token value used to access repository data to add comments and
      suggestions.
    required: true
    type: string

runs:
  using: "composite"
  steps:

    - name: "Check pull-request title follows conventional commits style"
      uses: amannn/action-semantic-pull-request@v5
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
