name: >
  Doc deploy dev action

description: |
  This action deploys the desired HTML documentation artifact containing the
  development version of a library to the specified branch of a repository. By
  default, the ``gh-pages`` branch of the current repository is assumed.

inputs:

  # Required inputs

  cname:
    description: >
      The canonical name (CNAME) containing the documentation.
    required: true
    type: string

  token:
    description: >
      Required password, key or token with the correct credentials for deploying the
      documentation. If deploying to the current repository, the ``secrets.GITHUB_TOKEN`` token
      is enough. For workflows deploying to other repositories, `generate and
      use a token with writing access
      <https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token>`_
      to that repository.
    required: true
    type: string

  # Optional inputs

  doc-artifact-name:
    description: >
        Name of the HTML documentation artifact. This artifact is expected to
        contain all the HTML and static files. If it contains a compressed file,
        make sure you enable the ``decompress-artifact`` option.
    required: false
    default: 'documentation-html'
    type: string

  decompress-artifact:
    description: >
      Wether to decompress the artifact using `ouch
      <https://github.com/ouch-org/ouch>`_ as decompression tool. Default value
      is ``false``.
    required: false
    default: false
    type: string

  repository:
    description: >
      Repository name in the form of ``username/repository`` to be used for
      deploying the documentation. The current repository is assumed by default.
    required: false
    default: 'current'
    type: string

  branch:
    description: >
      Branch name for deploying the documentation. The ``gh-pages`` branch is
      used by default.
    required: false
    default: 'gh-pages'
    type: string

  commit-message:
    description: >
      Commit message used when deploying the documentation.
    required: false
    default: 'DOC: update development documentation'
    type: string

  force-orphan:
    description: >
      Whether to force the deployment branch to be orphan with only the latest commit or not. Default value
      is ``true``.
    required: false
    default: true
    type: string

  content-element-id:
    description: >
      Identifier of the HTML tag that comprises all the content of the article
      or post.
    required: false
    default: 'main-content'
    type: string


runs:
  using: "composite"
  steps:

    # ------------------------------------------------------------------------

    - uses: ansys/actions/_logging@v4
      with:
        level: "INFO"
        message: >
          Checkout the repository branch for deploying the documentation. If
          this step fails, then it means that the provided token is not valid.

    - name: "Get the name of the repository"
      shell: bash
      run: |
        if [[ "${{ inputs.repository }}" == "current" ]]; then
          echo "REPOSITORY=${{ github.repository }}" >> $GITHUB_ENV
        else
          echo "REPOSITORY=${{ inputs.repository }}" >> $GITHUB_ENV
        fi

    - name: "Checkout ${{ env.REPOSITORY }} repository"
      uses: actions/checkout@v3
      with:
        repository: ${{ env.REPOSITORY }}
        ref: ${{ inputs.branch }}
        token: ${{ inputs.token }}

    # ------------------------------------------------------------------------

    - uses: ansys/actions/_logging@v4
      with:
        level: "INFO"
        message: >
          Download the documentation artifact from the current workflow. If the
          artifact contains a compressed file, decompress it. Display the
          structure of the 'version/dev' directory at the end of the process to
          verify the layout of the folder is the right one.

    - name: "Clean destination folder"
      shell: bash
      run:
        rm -rf version/dev && mkdir -p version/dev

    - name: "Download the development documentation artifact"
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.doc-artifact-name }}
        path: version/dev

    - name: "Update apt-get"
      shell: bash
      run: |
        sudo apt-get update

    - name: "Decompress artifact content"
      shell: bash
      if: inputs.decompress-artifact == 'true'
      run: |
        sudo apt-get install cargo && cargo install ouch && ouch --version
        cd version/dev && compressed_artifact=$(ls .)
        ouch decompress $compressed_artifact && rm $compressed_artifact

    - name: "Display structure of version/dev"
      shell: bash
      run: |
        ls -R version/dev

    # ------------------------------------------------------------------------

    - uses: ansys/actions/_logging@v4
      with:
        level: "INFO"
        message: >
          Create the 'versions.json' file if it does not exist. Note that this
          step is not required in the 'doc-deploy-stable' action. The reason is
          that for a stable release to be created, a development version must exist. This
          forces users to use this action before using the stable deploy one.

    - name: "Create the 'versions.json' file if not present"
      shell: bash
      run: |
        if ! [[ -f "versions.json" ]];
        then
            sudo apt-get install moreutils jq
            echo '[]' > versions.json
            url_dev="https://${{ inputs.cname }}/version/dev/"
            jq --arg url $url_dev '. += [{"name": "dev", "version": "dev", "url": $url}]' versions.json | sponge versions.json
        fi
        cat versions.json

    # ------------------------------------------------------------------------

    - uses: ansys/actions/_logging@v4
      with:
        level: "INFO"
        message: >
          Generate an 'index.html' for redirection to the latest stable version
          of the documentation. If no stable version has been released, a
          redirection to the development documentation is generated.


    - name: "Generate the redirection URL"
      shell: bash
      run: |
        if $(grep -q "(stable)" versions.json)
        then
          echo "Redirecting to the latest stable version..."
          echo "REDIRECTION_URL=https://${{ inputs.cname }}/version/stable/" >> $GITHUB_ENV
        else
          echo "Redirecting to the latest development version..."
          echo "REDIRECTION_URL=https://${{ inputs.cname }}/version/dev/" >> $GITHUB_ENV
        fi

    - name: "Create the 'index.html' redirection file"
      shell: bash
      run: |
        echo "<!DOCTYPE html>" > index.html
        echo "<meta charset=\"utf-8\">" >> index.html
        echo "<title>Redirecting to ${{ env.REDIRECTION_URL }}</title>" >> index.html
        echo "<meta http-equiv=\"refresh\" content=\"0; URL=${{ env.REDIRECTION_URL }}\">" >> index.html
        echo "<link rel=\"canonical\" href=\"${{ env.REDIRECTION_URL }}\">" >> index.html

    - name: "Show the contents of the 'index.html' redirection file"
      shell: bash
      run: |
          cat index.html

    # ------------------------------------------------------------------------

    - uses: ansys/actions/_logging@v4
      with:
        level: "INFO"
        message: >
          Create the '.nojekyll' and 'CNAME' file with the desired values

    - name: "Create '.nojekyll' and 'CNAME' files"
      shell: bash
      run: |
          touch .nojekyll CNAME
          echo "${{ inputs.cname }}" > CNAME

     # ------------------------------------------------------------------------

    - uses: ansys/actions/_logging@v4
      with:
        level: "INFO"
        message: >
          For deploying the documentation, a GitHub token or a deployment token
          is required. The GitHub token is used when deploying to the current
          repository while the deployment token is used to deploy to an external
          repository.

    - name: "Deploy to ${{ inputs.branch }} branch of ${{ github.repository }} repository"
      if: inputs.repository == 'current'
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_dir: .
        publish_branch: ${{ inputs.branch }}
        github_token: ${{ inputs.token }}
        commit_message: ${{ inputs.commit-message }}
        keep_files: true
        force_orphan: ${{ inputs.force-orphan }}

    - name: "Deploy to ${{ inputs.branch }} branch of ${{ inputs.repository }}"
      if: inputs.repository != 'current'
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_dir: .
        publish_branch: ${{ inputs.branch }}
        personal_token: ${{ inputs.token }}
        external_repository: ${{ inputs.repository }}
        commit_message: ${{ inputs.commit-message }}
        keep_files: true
        force_orphan: ${{ inputs.force-orphan }}
