name: "Check if the pull request title follows conventional commits."
description: "Action that checks if the title of the pull request is following the conventional commits standard."

runs:
  using: composite
  steps:
    - uses: amannn/action-semantic-pull-request@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
