---
title: Ansys Actions
format: cheat_sheet-pdf
version: main
footer: Getting started with Ansys action
footerlinks:
  - urls: 'https://actions.docs.ansys.com/version/stable/'
    text: Ansys action documentation
  - urls: 'https://github.com/ansys/actions/'
    text: Ansys action gitHub
execute:
    # output: false
    eval: false

latex-clean: true
jupyter:
  jupytext:
    text_representation:
      extension: .qmd
      format_name: quarto
      format_version: '1.0'
      jupytext_version: 1.16.1
  kernelspec:
    display_name: Python 3 (ipykernel)
    language: python
    name: python3
---

# branch name style

**Run branch name style checks**

```{python}
- uses: ansys/actions/branch-name-style@main

```

***Reference***: [Run branch name style checks](https://actions.docs.ansys.com/version/dev/style-actions/index.html#branch-name-style-action)


# build ci wheels

**Build a C-extension library**

```{python}
- name: Build a C-extension library wheel artifacts
  uses: ansys/actions/build-ci-library@main

```

***Reference***: [Build a C-extension library](https://actions.docs.ansys.com/version/dev/build-actions/index.html#build-ci-wheels-action)


# build library

**Build library basic example**

```{python}
- name: Build library source and wheel artifacts
  uses: ansys/actions/build-library@main
  with:
    library-name: ansys-<product>-<library>

```

***Reference***: [Build library basic example](https://actions.docs.ansys.com/version/dev/build-actions/index.html#build-library-action)


# build wheelhouse

**Build wheelhouse for latest Python versions**

```{python}
- name: Build a wheelhouse of the Python library
  uses: ansys/actions/build-wheelhouse@main
  with:
    library-name: <ansys-product-library>
    operating-system: ${{ matrix.os }}
    python-version: ${{ matrix.python-version }}

```

***Reference***: [Build wheelhouse for latest Python versions](https://actions.docs.ansys.com/version/dev/build-actions/index.html#build-wheelhouse-action)


# check licenses

**Check library dependencies ship with valid licenses**

```{python}
- name: Validate third party licenses
  uses: ansys/actions/check-licenses@main
  with:
    python-version: ${{ env.MAIN_PYTHON_VERSION }}

```

***Reference***: [Check library dependencies ship with valid licenses](https://actions.docs.ansys.com/version/dev/licenses-actions/index.html#check-licenses-action)


# check vulnerabilities

**Check library vulnerabilities (default mode - only on main)**

```{python}
- name: Check library vulnerabilities with default mode
  uses: ansys/actions/check-vulnerabilities@main
  with:
    python-package-name: ansys-<product>-<library>
    python-version: ${{ env.MAIN_PYTHON_VERSION }}
    token: ${{ secrets.PYANSYS_CI_BOT_TOKEN }}

```

***Reference***: [Check library vulnerabilities (default mode - only on main)](https://actions.docs.ansys.com/version/dev/vulnerability-actions/index.html#check-vulnerabilities-action)

# check vulnerabilities

**Check library vulnerabilities (development mode)**

```{python}
- name: Check library vulnerabilities with development mode
  uses: ansys/actions/check-vulnerabilities@main
  with:
    dev-mode: true
    python-package-name: ansys-<product>-<library>
    python-version: ${{ env.MAIN_PYTHON_VERSION }}
    token: ${{ secrets.PYANSYS_CI_BOT_TOKEN }}

```

***Reference***: [Check library vulnerabilities (development mode)](https://actions.docs.ansys.com/version/dev/vulnerability-actions/index.html#check-vulnerabilities-action)


# code style

**Running code style checks**

```{python}
- name: Run PyAnsys code style checks
  uses: ansys/actions/code-style@main

```

***Reference***: [Running code style checks](https://actions.docs.ansys.com/version/dev/style-actions/index.html#code-style-action)


# commit style

**Run commit style checks**

```{python}
- uses: ansys/actions/commit-style@main
  with:
    token: ${{ secrets.GITHUB_TOKEN }}

```

***Reference***: [Run commit style checks](https://actions.docs.ansys.com/version/dev/style-actions/index.html#commit-style-action)


# doc build

**Building library documentation**

```{python}
- name: Run Ansys documentation building action
  uses: ansys/actions/doc-build@main

```

***Reference***: [Building library documentation](https://actions.docs.ansys.com/version/dev/doc-actions/index.html#doc-build-action)

# doc build

**Installing additional system dependencies for building documentation**

```{python}
- name: Run Ansys documentation building action
  uses: ansys/actions/doc-build@main
  with:
    dependencies: graphviz mermaid-cli

```

***Reference***: [Installing additional system dependencies for building documentation](https://actions.docs.ansys.com/version/dev/doc-actions/index.html#doc-build-action)

# doc build

**Building library documentation that using XVFB**

```{python}
- name: Run Ansys documentation building action
  uses: ansys/actions/doc-build@main
  with:
    requires-xvfb: true

```

***Reference***: [Building library documentation that using XVFB](https://actions.docs.ansys.com/version/dev/doc-actions/index.html#doc-build-action)


# doc changelog

**Create changelog fragment**

```{python}
- uses: ansys/actions/doc-changelog@main
  with:
    token: ${{ secrets.PYANSYS_CI_BOT_TOKEN }}

```

***Reference***: [Create changelog fragment](https://actions.docs.ansys.com/version/dev/doc-actions/index.html#doc-changelog-action)


# doc deploy changelog

**Update CHANGELOG for new tag**

```{python}
- uses: ansys/actions/doc-deploy-changelog@main
  with:
    token: ${{ secrets.PYANSYS_CI_BOT_TOKEN }}

```

***Reference***: [Update CHANGELOG for new tag](https://actions.docs.ansys.com/version/dev/doc-actions/index.html#doc-deploy-changelog-action)


# doc deploy dev

**Deploy developers documentation**

```{python}
- name: Deploy the latest documentation
  uses: ansys/actions/doc-deploy-dev@main
  with:
    cname: <library>.docs.pyansys.com
    token: ${{ secrets.GITHUB_TOKEN }}

```

***Reference***: [Deploy developers documentation](https://actions.docs.ansys.com/version/dev/doc-actions/index.html#doc-deploy-dev-action)


# doc deploy index

**Index the documentation and scrap using pymeilisearch**

```{python}
- name: Deploy the latest documentation index
  uses: ansys/actions/doc-deploy-index@main
  with:
    api-key: ${{ secrets.MEILISEARCH-API-KEY }}
    cname: <library>.docs.pyansys.com/version/<version-number>
    host-url: <meilisearch-host-url>
    index-name: <index-name>

```

***Reference***: [Index the documentation and scrap using pymeilisearch](https://actions.docs.ansys.com/version/dev/doc-actions/index.html#doc-deploy-index-action)


# doc deploy stable

**Deploy stable documentation**

```{python}
- name: Deploy the stable documentation
  uses: ansys/actions/doc-deploy-stable@main
  with:
    cname: <library>.docs.pyansys.com
    token: ${{ secrets.GITHUB_TOKEN }}

```

***Reference***: [Deploy stable documentation](https://actions.docs.ansys.com/version/dev/doc-actions/index.html#doc-deploy-stable-action)


# doc style

**Running documentation style checks**

```{python}
- name: Running documentation style checks
  uses: ansys/actions/doc-style@main
  with:
    token: ${{ secrets.GITHUB_TOKEN }}

```

***Reference***: [Running documentation style checks](https://actions.docs.ansys.com/version/dev/style-actions/index.html#doc-style-action)


# docker style

**Docker style**

```{python}
- uses: ansys/actions/docker-style@main
  with:
    directory: docker
    error-level: 1
    recursive: true

```

***Reference***: [Docker style](https://actions.docs.ansys.com/version/dev/style-actions/index.html#docker-style-action)


# hk package clean except

**Perform versions cleanup - except certain tags**

```{python}
- name: Perform versions cleanup - except certain tags
  uses: ansys/actions/hk-package-clean-except@main
  with:
    package-name: mypackage
    tags-kept: latest, latest-unstable
    token: ${{ secrets.GITHUB_TOKEN }}

```

***Reference***: [Perform versions cleanup - except certain tags](https://actions.docs.ansys.com/version/dev/housekeeping-actions/index.html#hk-package-clean-except-action)


# hk package clean untagged

**Perform untagged versions cleanup**

```{python}
- name: Perform untagged versions cleanup
  uses: ansys/actions/hk-package-clean-untagged@main
  with:
    package-name: mypackage
    token: ${{ secrets.GITHUB_TOKEN }}

```

***Reference***: [Perform untagged versions cleanup](https://actions.docs.ansys.com/version/dev/housekeeping-actions/index.html#hk-package-clean-untagged-action)


# release github

**Release to GitHub**

```{python}
- name: Release to GitHub
  uses: ansys/actions/release-github@main
  with:
    library-name: ansys-<product>-<library>

```

***Reference***: [Release to GitHub](https://actions.docs.ansys.com/version/dev/release-actions/index.html#release-github-action)


# release pypi private

**Release to private PyPI**

```{python}
- name: Release to the private PyPI repository
  uses: ansys/actions/release-pypi-private@main
  with:
    library-name: ansys-<product>-<library>
    twine-token: ${{ secrets.PYANSYS_PYPI_PRIVATE_PAT }}
    twine-username: __token__

```

***Reference***: [Release to private PyPI](https://actions.docs.ansys.com/version/dev/release-actions/index.html#release-pypi-private-action)


# release pypi public

**Release to public PyPI**

```{python}
- name: Release to the public PyPI repository
  uses: ansys/actions/release-pypi-public@main
  with:
    library-name: ansys-<product>-<library>
    twine-token: ${{ secrets.PYPI_TOKEN }}
    twine-username: __token__

```

***Reference***: [Release to public PyPI](https://actions.docs.ansys.com/version/dev/release-actions/index.html#release-pypi-public-action)

# release pypi public

**Release to public PyPI using Trusted Publisher**

```{python}
- name: Release to the public PyPI repository using Trusted Publisher
  uses: ansys/actions/release-pypi-public@main
  with:
    library-name: ansys-<product>-<library>
    use-trusted-publisher: true

```

***Reference***: [Release to public PyPI using Trusted Publisher](https://actions.docs.ansys.com/version/dev/release-actions/index.html#release-pypi-public-action)


# release pypi test

**Release to test PyPI**

```{python}
- name: Release to the test PyPI repository
  uses: ansys/actions/release-pypi-test@main
  with:
    library-name: ansys-<product>-<library>
    twine-token: ${{ secrets.PYANSYS_PYPI_TEST_PAT }}
    twine-username: __token__

```

***Reference***: [Release to test PyPI](https://actions.docs.ansys.com/version/dev/release-actions/index.html#release-pypi-test-action)


# tests pytest

**Testing library with different operating systems and Python versions**

```{python}
- name: Run pytest
  uses: ansys/actions/tests-pytest@main
  with:
    pytest-extra-args: --cov=ansys.<library> --cov-report=term --cov-report=html:.cov/html
    pytest-markers: -k 'mocked'

```

***Reference***: [Testing library with different operating systems and Python versions](https://actions.docs.ansys.com/version/dev/tests-actions/index.html#tests-pytest-action)

# tests pytest

**Optimized testing with different operating systems and Python versions**

```{python}
- name: Login into the GitHub container registry
  uses: docker/login-action@v2.1.0
  with:
    password: ${{ secrets.GITHUB_TOKEN }}
    registry: ghcr.io
    username: ${{ secrets.GH_USERNAME }}
- env:
    LICENSE_SERVER: ${{ secrets.LICENSE_SERVER }}
  name: Pull, launch and verify desired Ansys service
  run: '...'
- name: Run pytest with desired markers and extra arguments
  uses: ansys/actions/tests-pytest@main
  with:
    pytest-extra-args: ${{ matrix.cfg.extra-args }}
    pytest-markers: ${{ matrix.cfg.markers }}
    requires-xvfb: true

```

***Reference***: [Optimized testing with different operating systems and Python versions](https://actions.docs.ansys.com/version/dev/tests-actions/index.html#tests-pytest-action)
