# Copyright (C) 2022 - 2025 ANSYS, Inc. and/or its affiliates.
# SPDX-License-Identifier: MIT
#
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

name: |
  Check actions security action.

description: |
  Detects common security issues in GitHub Actions yml files using `zizmor <https://woodruffw.github.io/zizmor/>`_.

inputs:

  token:
    description: |
      Use the ``GH_TOKEN`` to allow online audits by zizmor.
    required: false
    type: string

  generate-summary:
    description: |
      Whether to output a nicely formatted summary table showing the number
      of security issues per workflow file.
    required: false
    default: true
    type: boolean

  auditing-level:
    description: |
      Equivalent to 'persona' zizmor option, controls zizmor's auditing sensitivity.
      Possible values include 'normal', 'high', and 'strict', which map to 'regular', 'pedantic',
      and 'auditor' persona options.
    required: false
    default: 'high'
    type: string

  trust-ansys-actions:
    description: |
      Whether to trust the ``ansys/actions``. Setting this option to true will allow using tags
      with ``ansys/actions``.
    required: false
    default: true
    type: boolean

runs:
  using: "composite"
  steps:
    - name: "Install Git and clone project"
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: "Install uv"
      uses: astral-sh/setup-uv@0c5e2b8115b80b4c7c5ddf6ffdd634974642d182 # v5.4.1

    - name: "Install zizmor and verify installation"
      shell: bash
      run: |
        uv tool install zizmor==1.6.0
        zizmor --version

    - name: "Optionally set GH_TOKEN"
      if: ${{ inputs.token != '' }}
      shell: bash
      run: |  # zizmor: ignore[template-injection]
        echo 'GH_TOKEN=${{ inputs.token }}' >> "$GITHUB_ENV"

    - name: "Write zizmor config file"
      shell: bash
      env:
        ANSYS_ACTIONS_POLICY: ${{ inputs.trust-ansys-actions == 'true' && 'ref-pin' || 'hash-pin' }}
      run: |
        cat << _EOF_ > .zizmor.yml
        rules:
          unpinned-uses:
            config:
              policies:
                ansys/*: ${ANSYS_ACTIONS_POLICY}
                actions/*: hash-pin
        _EOF_

    - name: "Output a summary of detected vulnerabilities"
      if: ${{ inputs.generate-summary == 'true' }}
      shell: bash
      env:
        HIGH_AUDIT_LEVEL: ${{ inputs.auditing-level == 'high' && '--persona=pedantic' || '' }}
        STRICT_AUDIT_LEVEL: ${{ inputs.auditing-level == 'strict' && '--persona=auditor' || '' }}
      run: |
        cat << _EOF_ > zizmor-summary
        #!/bin/bash
        # Process zizmor report and generate summary of identified issues

        format="%-50s%-20s\n"
        printf "\$format" "=========" "================"
        printf "\$format" "File name" "Number of issues"
        printf "\$format" "=========" "================"

        count=0
        while read no_of_occurence workflow_file; do
            printf "\$format" "\$workflow_file" "\$no_of_occurence"
            count=\$((count + no_of_occurence))
        done < <(zizmor $HIGH_AUDIT_LEVEL $STRICT_AUDIT_LEVEL . 2> /dev/null | grep -Eo "[^ /]+/([^ /]+/)?.*\.yml" | sort | uniq -c)

        printf "\$format" "=========" "================"
        printf "\$format" "Total" "\$count"
        printf "\$format" "=========" "================"
        printf "\nNote: the summary excludes warning surpressed by zizmor."
        _EOF_

        chmod u+x zizmor-summary
        ./zizmor-summary

    - name: "Detailed zizmor audit"
      shell: bash
      env:
        HIGH_AUDIT_LEVEL: ${{ inputs.auditing-level == 'high' && '--persona=pedantic' || '' }}
        STRICT_AUDIT_LEVEL: ${{ inputs.auditing-level == 'strict' && '--persona=auditor' || '' }}
      run: |
        zizmor ${HIGH_AUDIT_LEVEL} ${STRICT_AUDIT_LEVEL} .
