# Copyright (C) 2022 - 2024 ANSYS, Inc. and/or its affiliates.
# SPDX-License-Identifier: MIT
#
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

name: >
  Documentation build action

description: |
  Build library documentation using `Sphinx
  <https://www.sphinx-doc.org/en/master/>`_. The action installs documentation
  dependencies provided either in a requirement file, e.g.
  ``requirements/requirements_doc.txt``, or in the ``[doc]`` section of the
  additional dependencies in the ``pyproject.toml`` file. Assuming that
  `sphinx-build
  <https://www.sphinx-doc.org/en/master/man/sphinx-build.html>`_ is available
  after installing the documentation dependencies, the action uses it
  to generate documentation from the source. It requires that all the
  documentation is contained in the ``doc/`` directory of a project. The
  action locates the ``doc/Makefile`` and runs the ``make html`` and
  ``make pdf`` commands. If desired, the ``make json`` command can
  also be executed to generate JSON documentation.

inputs:

  # Required inputs

  sphinxopts:
    description: |
      Set of options to pass to the ``Sphinx`` builder.

      .. note::

          This will override the ``SPHINXOPTS`` declared in your Makefile.

    required: true
    type: string

  dependencies:
    description: >
      String of system dependencies to be installed before building the
      documentation of the project.
    required: true
    type: string

  skip-dependencies-cache:
    description: >
      Whether to ignore dependencies cache or not - for OS libraries.
    required: true
    type: boolean

  requires-xvfb:
    description: |
      Whether to install `X Virtual Frame Buffer (XVFB)
      <https://www.x.org/releases/X11R7.6/doc/man/man1/Xvfb.1.xhtml>`_ and run
      the whole test session using XVFB.
    required: true
    type: boolean

  skip-install:
    description: >
      Whether to skip the installation of the project.
      Pure documentation projects require that this action be set to ``false``
      because there is no Python library associated with the project.
    required: true
    type: boolean

  requirements-file:
    description: >
      Path to the requirements file in case it needs to be in a specific location.
      This is useful for non python projects, where you don't necessarily have a requirements
      file in the root of the project.
    required: true
    type: string

  skip-json-build:
    description: >
      Whether to skip the generation of JSON documentation.
    required: true
    type: boolean

  check-links:
    description: >
      Whether to perform external link checks during the generation of
      documentation.
    required: true
    type: boolean

  add-pdf-html-docs-as-assets:
    description: |
      Whether to add PDF and HTML documentation as assets of the HTML
      documentation. The HTML documentation is compressed before being added.
      The PDF file name is expected to be retrieved through the documentation's
      configuration file 'conf.py' in 'doc/source'.

      .. warning::

          The HTML files are expected to be contained in ``doc/_build`` and the
          PDF file is copied in ``doc/_build/html/_static/assets/download``.
          If such directories do not exist in your repo, the action will fail.

    required: true
    type: boolean


runs:
  using: "composite"
  steps:

    - name: "Collect system dependencies"
      shell: bash
      run: |
        if [[ ${{ inputs.requires-xvfb }} == 'true' ]]; then
          echo "NEEDED_DEPS=$(echo '${{ inputs.dependencies }} xvfb')" >> $GITHUB_ENV
        else
          echo "NEEDED_DEPS=$(echo '${{ inputs.dependencies }}')" >> $GITHUB_ENV
        fi

    - name: "Cache apt packages needed"
      uses: awalsh128/cache-apt-pkgs-action@v1.3.1
      if: inputs.skip-dependencies-cache == 'false' && env.NEEDED_DEPS != ''
      with:
        packages: ${{ env.NEEDED_DEPS }}
        version: 1.0

    - name: "Update apt-get"
      shell: bash
      run: |
        sudo apt-get update

    - name: "Install system dependencies"
      shell: bash
      run: |
        sudo apt-get install -y ${{ env.NEEDED_DEPS }}

    - name: "Install LaTeX"
      shell: bash
      run: |
        sudo apt-get install -y texlive-latex-extra latexmk

    - name: "Check if requirements.txt file exists"
      shell: bash
      run: |
        echo "EXISTS_DOC_REQUIREMENTS=$(if [ -f ${{ inputs.requirements-file }} ]; then echo 'true'; else echo 'false'; fi)" >> $GITHUB_ENV

    - name: "Print previous output"
      shell: bash
      run: |
        echo "Output was found ${{ env.EXISTS_DOC_REQUIREMENTS }}"

    - name: "Update pip"
      shell: bash
      run: python -m pip install -U pip

    - name: "Install documentation dependencies from requirements file"
      shell: bash
      if: env.EXISTS_DOC_REQUIREMENTS == 'true'
      run: |
        python -m pip install -r ${{ inputs.requirements-file }}

    - name: "Install Python library"
      shell: bash
      if: inputs.skip-install == 'false'
      run: |
        python -m pip install .

    - name: "Install documentation dependencies from pyproject.toml"
      shell: bash
      if: env.EXISTS_DOC_REQUIREMENTS == 'false'
      run: |
        if grep -q 'build-backend = "poetry\.core\.masonry\.api"' "pyproject.toml"; then
          python -m pip install poetry
          poetry install --with doc
        else
          python -m pip install .[doc]
        fi

    - name: "Determine make command context"
      shell: bash
      run: |
        if grep -q 'build-backend = "poetry\.core\.masonry\.api"' "pyproject.toml"; then
          echo "SPHINX_BUILD_MAKE=$(echo 'poetry run -- make')" >> $GITHUB_ENV
        else
          echo "SPHINX_BUILD_MAKE=$(echo 'make')" >> $GITHUB_ENV
        fi

    - name: "Build HTML, PDF, and JSON documentation"
      if: inputs.requires-xvfb == 'false'
      shell: bash
      run: |
        ${{ env.SPHINX_BUILD_MAKE }} -C doc html SPHINXOPTS="${{ inputs.sphinxopts }}"
        ${{ env.SPHINX_BUILD_MAKE }} -C doc pdf
        if [[ ${{ inputs.check-links }} == 'true' ]];
        then
          ${{ env.SPHINX_BUILD_MAKE }} -C doc linkcheck SPHINXOPTS="${{ inputs.sphinxopts }}"
        fi
        if [[ ${{ inputs.skip-json-build }} == 'false' ]];
        then
          ${{ env.SPHINX_BUILD_MAKE }} -C doc json SPHINXOPTS="${{ inputs.sphinxopts }}"
        fi

    - name: "Build HTML, PDF, and JSON documentation using xvfb"
      if: inputs.requires-xvfb == 'true'
      shell: bash
      run: |
        xvfb-run ${{ env.SPHINX_BUILD_MAKE }} -C doc html SPHINXOPTS="${{ inputs.sphinxopts }}"
        xvfb-run ${{ env.SPHINX_BUILD_MAKE }} -C doc pdf
        if [[ ${{ inputs.check-links }} == 'true' ]];
        then
          xvfb-run ${{ env.SPHINX_BUILD_MAKE }} -C doc linkcheck SPHINXOPTS="${{ inputs.sphinxopts }}"
        fi
        if [[ ${{ inputs.skip-json-build }} == 'false' ]];
        then
          xvfb-run ${{ env.SPHINX_BUILD_MAKE }} -C doc json SPHINXOPTS="${{ inputs.sphinxopts }}"
        fi

    # ------------------------------------------------------------------------

    - uses: ansys/actions/_logging@v6.1
      if: ${{ inputs.add-pdf-html-docs-as-assets == 'true' }}
      with:
        level: "INFO"
        message: >
          Set environment variable PDF_FILENAME.

    - name: Parse PDF file name
      if: ${{ inputs.add-pdf-html-docs-as-assets == 'true' }}
      shell: bash
      run: |
        python ${{ github.action_path }}/../doc-build/parse_doc_conf.py

    - uses: ansys/actions/_logging@v6.1
      if: ${{ (inputs.add-pdf-html-docs-as-assets == 'true' ) && (env.PDF_FILENAME == '') }}
      with:
        level: "ERROR"
        message: >
          Unable to determine PDF filename using conf.py file.

    - uses: ansys/actions/_logging@v6.1
      if: ${{ (inputs.add-pdf-html-docs-as-assets == 'true' ) && (env.PDF_FILENAME != '') }}
      with:
        level: "INFO"
        message: >
          Environment variable PDF_FILENAME set to ${{ env.PDF_FILENAME }}.

    # ------------------------------------------------------------------------
    - uses: ansys/actions/_logging@v6.1
      if: ${{ inputs.add-pdf-html-docs-as-assets == 'true' }}
      with:
        level: "INFO"
        message: >
          Check if expected directories exist.

    - name: Set expected build directory
      if: ${{ inputs.add-pdf-html-docs-as-assets == 'true' }}
      shell: bash
      run: |
        echo "EXPECTED_BUILD_DIR=doc/_build" >> $GITHUB_ENV

    - name: Check expected build directory
      if: ${{ inputs.add-pdf-html-docs-as-assets == 'true' }}
      shell: bash
      run: |
        echo "EXISTS_EXPECTED_BUILD_DIR=$( [ -d ${{ env.EXPECTED_BUILD_DIR }} ] && echo 'true' || echo 'false' )" >> $GITHUB_ENV

    - uses: ansys/actions/_logging@v6.1
      if: ${{ (inputs.add-pdf-html-docs-as-assets == 'true') && (env.EXISTS_EXPECTED_BUILD_DIR == 'false') }}
      with:
        level: "ERROR"
        message: >
          Expected build directory ${{ env.EXPECTED_BUILD_DIR }} does not exist.

    - name: Set expected download directory
      if: ${{ inputs.add-pdf-html-docs-as-assets == 'true' }}
      shell: bash
      run: |
        echo "EXPECTED_DOWNLOAD_DIR=$(echo '${{ env.EXPECTED_BUILD_DIR }}/html/_static/assets/download')" >> $GITHUB_ENV

    - name: Check expected download directory
      if: ${{ inputs.add-pdf-html-docs-as-assets == 'true' }}
      shell: bash
      run: |
        echo "EXISTS_EXPECTED_DOWNLOAD_DIR=$( [ -d '${{ env.EXPECTED_DOWNLOAD_DIR }}' ] && echo 'true' || echo 'false' )" >> $GITHUB_ENV

    - uses: ansys/actions/_logging@v6.1
      if: ${{ (inputs.add-pdf-html-docs-as-assets == 'true') && (env.EXISTS_EXPECTED_DOWNLOAD_DIR == 'false') }}
      with:
        level: "WARNING"
        message: >
          Expected build directory ${{ env.EXPECTED_DOWNLOAD_DIR }} does not exist. Creating it...

    - name: Create expected download directory
      if: ${{ (inputs.add-pdf-html-docs-as-assets == 'true') && (env.EXISTS_EXPECTED_DOWNLOAD_DIR == 'false') }}
      shell: bash
      run: |
        mkdir -p ${{ env.EXPECTED_DOWNLOAD_DIR }}

    # ------------------------------------------------------------------------

    - name: Check build directory
      if: ${{ inputs.add-pdf-html-docs-as-assets == 'true' }}
      uses: ansys/actions/_logging@v6.1
      with:
        level: "INFO"
        message: >
          Add PDF and HTML documentation as assets.

    - name: Compress HTML documentation
      if: ${{ inputs.add-pdf-html-docs-as-assets == 'true' }}
      uses: vimtor/action-zip@v1.2
      with:
        files: ${{ env.EXPECTED_BUILD_DIR }}/html
        dest: documentation-html.zip

    - name: Add assets to HTML docs
      if: ${{ inputs.add-pdf-html-docs-as-assets == 'true' }}
      shell: bash
      run: |
        mv documentation-html.zip ${{ env.EXPECTED_DOWNLOAD_DIR }}
        if [ -e  "${{ env.EXPECTED_BUILD_DIR }}/latex/${{ env.PDF_FILENAME }}" ]; then
            cp ${{ env.EXPECTED_BUILD_DIR }}/latex/${{ env.PDF_FILENAME }} ${{ env.EXPECTED_DOWNLOAD_DIR }}
            echo "File ${{ env.EXPECTED_BUILD_DIR }}/latex/${{ env.PDF_FILENAME }} has been copied."
        else
            cp ${{ env.EXPECTED_BUILD_DIR }}/latex/*.pdf ${{ env.EXPECTED_DOWNLOAD_DIR }}
            echo "Couldn't find ${{ env.EXPECTED_BUILD_DIR }}/latex/${{ env.PDF_FILENAME }}, every existing PDF file has been copied."
        fi

    # ------------------------------------------------------------------------

    - name: "Upload HTML documentation artifact"
      uses: actions/upload-artifact@v4
      with:
        name: documentation-html
        path: doc/_build/html
        retention-days: 7

    - name: "Upload PDF documentation artifact"
      uses: actions/upload-artifact@v4
      with:
        name: documentation-pdf
        path: doc/_build/latex/*.pdf
        retention-days: 7

    - name: "Upload JSON documentation artifact"
      uses: actions/upload-artifact@v4
      if: inputs.skip-json-build == 'false'
      with:
        name: documentation-json
        path: doc/_build/json
        retention-days: 7
