# Copyright (C) 2022 - 2024 ANSYS, Inc. and/or its affiliates.
# SPDX-License-Identifier: MIT
#
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

name: "Automerge dependabot and pre-commit.ci PRs"
description: "Action merging dependabot and pre-commit.ci PRs."

inputs:
  approver:
    description: "Approver GitHub ID."
    required: true
    type: string
  approver-token:
    description: "Approver GitHub token."
    required: true
    type: string

runs:
  using: "composite"
  steps:

    - name: Verify allowed PRs (dependabot and pre-commit.ci)
      shell: bash
      run: |
        if [[ ${{ github.head_ref }} == 'dependabot/'* ]] || [[ ${{ github.head_ref }} == 'pre-commit-ci-update-config' ]]; then
          echo "PR is allowed to be automerged."
          echo "SKIP_ACTION=0" >> $GITHUB_ENV
        else
          echo "PR is not allowed to be automerged. Exiting gracefully..."
          echo "SKIP_ACTION=1" >> $GITHUB_ENV
          exit 0
        fi

        # If it is a dependabot PR, create a new variable (bool type)
        # to be used in the next steps.
        if [[ ${{ github.head_ref }} == 'dependabot/'* ]]; then
          echo "DEPENDABOT_PR=1" >> $GITHUB_ENV
        else
          echo "DEPENDABOT_PR=0" >> $GITHUB_ENV
        fi

    - name: Approve a PR
      shell: bash
      if: ${{ env.SKIP_ACTION == '0' }}
      run: gh pr review --approve "$PR_URL"
      env:
        PR_URL: ${{ github.event.pull_request.html_url }}
        GH_TOKEN: ${{ inputs.approver-token }}

    - name: Merge a PR
      shell: bash
      if: ${{ env.SKIP_ACTION == '0' }} && ${{ env.DEPENDABOT_PR == '0' }}
      run: gh pr merge --auto --squash "$PR_URL"
      env:
        PR_URL: ${{ github.event.pull_request.html_url }}
        GH_TOKEN: ${{ inputs.approver-token }}

    # On dependabot PRs, auto-merge is only enabled iif it is a patch
    # or minor version bump. Major version bumps are not auto-merged.
    - name: Dependabot metadata (if dependabot PR only)
      if: ${{ env.SKIP_ACTION == '0' }} && ${{ env.DEPENDABOT_PR == '1' }}
      id: metadata
      uses: dependabot/fetch-metadata@v2
      with:
        github-token: ${{ inputs.approver-token }}

    - name: Enable auto-merge for Dependabot PRs
      shell: bash
      if: ${{ env.SKIP_ACTION == '0' }} && ${{ env.DEPENDABOT_PR == '1' }}
      run: |
        if [[ ${{ steps.metadata.outputs.update-type }} != 'version-update:semver-major' ]]; then
          gh pr merge --auto --squash "$PR_URL"
        else
          echo "Major version bump detected. Skipping auto-merge."
        fi
      env:
        PR_URL: ${{ github.event.pull_request.html_url }}
        GH_TOKEN: ${{ inputs.approver-token }}
