name: >
  Doc deploy stable action

description: |
  This action deploys the desired HTML documentation artifact containing the
  stable version of a library to the specified branch of a repository. By
  default, the ``gh-pages`` branch of the current repository is assumed.

  .. note::

      If your project is using ``pyansys/actions@v3`` or lower and you would
      like to update to this version of the actions, see the `guidelines for
      migrating to the latest multi-version documentaion layout
      <https://dev.docs.pyansys.com/how-to/documenting/multi-versio-migration-from-pyansys/actions@v3-to-pyansys/actions@v4>`_.

inputs:

  # Required inputs

  cname:
    description: >
      The canonical name (CNAME) containing the documentation.
    required: true
    type: string

  token:
    description: >
      Required password, key or token with the correct credentials for deploying the
      documentation. If deploying to the current repository, the ``secrets.GITHUB_TOKEN`` token is
      is enough. For workflows deploying to other repositories, `generate and
      use a token with writing access
      <https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token>`_
      to that repository.
    required: true
    type: string

  # Optional inputs

  doc-artifact-name:
    description: >
        Name of the HTML documentation artifact. This artifact is expected to
        contain all the HTML and static files. If it contains a compressed file,
        make sure you enable the ``decompress-artifact`` option.
    required: false
    default: 'documentation-html'
    type: string

  decompress-artifact:
    description: >
      Whether to decompress the ``doc-artifact-name`` file using `ouch
      <https://github.com/ouch-org/ouch>`_ as decompression tool. Default value
      is ``false``.
    required: false
    default: false
    type: string

  repository:
    description: >
      Repository name in the form of ``username/repository`` to be used for
      deploying the documentation. The current repository is assumed by default.
    required: false
    default: 'current'
    type: string

  branch:
    description: >
      Branch name for deploying the documentation. The ``gh-pages`` branch is
      used by default.
    required: false
    default: 'gh-pages'
    type: string

  commit-message:
    description: >
      Commit message used when deploying the documentation.
    required: false
    default: 'DOC: update development documentation'
    type: string

  render-last:
    description: >
      The number of stable versions to be shown in the `version drop-down
      <https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/version-dropdown.html>`_.
    default: '3'
    required: false
    type: string

runs:
  using: "composite"
  steps:

    # ------------------------------------------------------------------------

    - uses: pyansys/actions/_logging@main
      with:
        level: "INFO"
        message: >
          Collect the version number from the tag or the branch name according
          to the reference type. Tags names are expected to follow
          'v<MAJOR>.<MINOR>' or 'v<MAJOR>.<MINOR>.<PATCH>'. Braches must follow
          'release/<MAJOR>.<MINOR>'.

    - name: "Collect version number from the tag"
      shell: bash
      if: github.ref_type == 'tag'
      run: |
        tag=${{ github.ref_name }}
        version=$( echo $tag | cut -d 'v' -f 2)

        if [[ $version =~ ^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)$ ]]; then
          echo "VERSION_RAW=$(echo $version)" >> $GITHUB_ENV
        else
          echo -e "\033[1;91m[ERROR]: Tag names must follow 'v<MAJOR>.<MINOR>.<PATCH> name convention.'\033[0m"
          exit 1
        fi

    - name: "Collect version number from the release branch"
      shell: bash
      if: github.ref_type == 'branch'
      run: |
        tag=${{ github.ref_name }}
        version=$( echo $tag | cut -d 'release/' -f 2)

        if [[ $version =~ ^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)$ ]]; then
          echo "VERSION_RAW=$(echo $version)" >> $GITHUB_ENV
        else
          echo -e "\033[1;91m[ERROR]: Branch names must follow 'release/<MAJOR>.<MINOR>' name convention.\033[0m"
          exit 1
        fi

    - name: "Assemble the version number using the collected major and minor numbers"
      shell: bash
      run: |
          major=$(echo ${{ env.VERSION_RAW }} | cut -d . -f 1)
          minor=$(echo ${{ env.VERSION_RAW }} | cut -d . -f 2)
          echo "VERSION=$major.$minor" >> $GITHUB_ENV

    # ------------------------------------------------------------------------

    - uses: pyansys/actions/_logging@main
      with:
        level: "INFO"
        message: >
          Checkout the repository branch for deploying the documentation. If this
          step fails, then it means that the provided token is not valid.

    - name: "Get the name of the repository"
      shell: bash
      run: |
        if [[ "${{ inputs.repository }}" == "current" ]]; then
          echo "REPOSITORY=${{ github.repository }}" >> $GITHUB_ENV
        else
          echo "REPOSITORY=${{ inputs.repository }}" >> $GITHUB_ENV
        fi

    - name: "Checkout ${{ env.REPOSITORY }} repository"
      uses: actions/checkout@v3
      with:
        repository: ${{ env.REPOSITORY }}
        ref: ${{ inputs.branch }}
        token: ${{ inputs.token }}

    # ------------------------------------------------------------------------

    - uses: pyansys/actions/_logging@main
      with:
        level: "INFO"
        message: >
          Download the stable documentation artifact in a folder that has the same
          name as the version number. Decompress artifact if required. Finally,
          display the structure of the directory to verify that it has the right
          layout.

    - name: "Clean version content"
      shell: bash
      run: |
        if [ -d version/${{ env.VERSION }} ]; then
          echo "VERSION_EXISTS=true" >> $GITHUB_ENV
        else
          echo "VERSION_EXISTS=false" >> $GITHUB_ENV
        fi
        rm -rf version/${{ env.VERSION }} && mkdir -p version/${{ env.VERSION }}

    - name: "Download the stable documentation artifact"
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.doc-artifact-name }}
        path: version/${{ env.VERSION }}

    - name: "Decompress artifact content"
      shell: bash
      if: inputs.decompress-artifact == 'true'
      run: |
        sudo apt-get install cargo && cargo install ouch && ouch --version
        cd version/${{ env.VERSION }} && compressed_artifact=$(ls .)
        ouch decompress $compressed_artifact && rm $compressed_artifact

    - name: "Display structure of version/dev"
      shell: bash
      run: |
        ls -R version/${{ env.VERSION }}

    # ------------------------------------------------------------------------

    - uses: pyansys/actions/_logging@main
      with:
        level: "INFO"
        message: >
          Collect all stable releases (X.Y). Crop until matching the desired
          number to be displayed in the switcher. Generate the 'versions.json'
          file including development and latest stable links.

    - name: "Install 'sponge' and 'jq' for manipulating JSON files"
      shell: bash
      run: |
        sudo apt-get install moreutils jq

    - name: "Create a clean 'versions.json' file"
      shell: bash
      run: |
        rm -rf versions.json && touch versions.json && echo '[]' > versions.json

    - name: "Add the development version to the 'versions.json' file"
      shell: bash
      run: |
        url_dev="https://${{ inputs.cname }}/version/dev/"
        jq --arg url $url_dev '. += [{"name": "dev", "version": "dev", "url": $url}]' versions.json | sponge versions.json
        cat versions.json

    - name: "Populate the 'versions.json' file with the desired amount of versions"
      shell: bash
      run: |
        for version in $( ls version | \
                          grep -E "^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)$" | \
                          sort -r --version-sort | \
                          head -${{ inputs.render-last }}); do
          url="https://${{ inputs.cname }}/version/$version/"
          jq --arg version $version --arg url $url '. += [{"name": $version, "version": $version, "url": $url}]' < versions.json | sponge versions.json
        done

        cat versions.json

    - name: "Convert the first stable version into the 'stable' one"
      shell: bash
      run: |
        jq '.[1].name += " (stable)"' versions.json | sponge versions.json
        url_stable="https://${{ inputs.cname }}/version/stable/"
        jq --arg url $url_stable '.[1].url = $url' versions.json | sponge versions.json
        cat versions.json

    - name: "Find the latest stable version"
      shell: bash
      run: |
        stable_version=$(jq '.[1].version' versions.json | grep -o '".*"' | sed 's/"//g')
        echo "LATEST_STABLE_VERSION=$stable_version" >> $GITHUB_ENV

    - name: "Update the content for the 'version/stable' folder"
      shell: bash
      run: |
        rm -rf version/stable && cp -r version/${{ env.LATEST_STABLE_VERSION }} version/stable

    # ------------------------------------------------------------------------

    - uses: pyansys/actions/_logging@main
      with:
        level: "INFO"
        message: >
          Generate the content for the announcement file. Place a copy of this
          file in each one of outdated stable versions. 

    - name: "Generate the template content for the 'announcement.html' file"
      shell: bash
      run: |
        cat > announcement.html <<'EOF'  
          <p>
            You are not viewing the most recent version of this documentation.
            The latest stable release is <a href="STABLE_URL">LATEST_STABLE_VERSION</a>
          </p>
        EOF

    - name: "Render the 'announcement.html' template with the desired stable version"
      shell: bash
      run: |
        latest_stable_version=${{ env.LATEST_STABLE_VERSION}}
        stable_url="https://${{ inputs.cname }}/version/stable/"
        sed -i "s|LATEST_STABLE_VERSION|$latest_stable_version|g" announcement.html
        sed -i "s|STABLE_URL|$stable_url|g" announcement.html

    - name: "Place the 'announcement.html' file in every public folder of all the outdated versions"
      shell: bash
      run: |
        for version_dir in $( ls version | \
                          grep -E "^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)$" | \
                          grep -v "${{ env.LATEST_STABLE_VERSION }}" | \
                          sort -r --version-sort ); do
            find version/$version_dir -type d -not \( -path "*/_*" -type d -prune \) -exec cp announcement.html {} \;
        done

    - name: "Delete the 'announcement.html' file used as template"
      shell: bash
      run: |
        rm -rf announcement.html

    # ------------------------------------------------------------------------

    - uses: pyansys/actions/_logging@main
      with:
        level: "INFO"
        message: >
          Generate the redirection link. Since this is the stable documentation
          deployment action, there is always a 'version/stable' folder. Hence,
          redirection link always points to this folder.

    - name: "Generate the redirection URL"
      shell: bash
      run: |
        echo "REDIRECTION_URL=https://${{ inputs.cname }}/version/stable/" >> $GITHUB_ENV

    - name: "Create the 'index.html' redirection file"
      shell: bash
      run: |
        echo "<!DOCTYPE html>" > index.html
        echo "<meta charset=\"utf-8\">" >> index.html
        echo "<title>Redirecting to ${{ env.REDIRECTION_URL }}</title>" >> index.html
        echo "<meta http-equiv=\"refresh\" content=\"0; URL=${{ env.REDIRECTION_URL }}\">" >> index.html
        echo "<link rel=\"canonical\" href=\"${{ env.REDIRECTION_URL }}\">" >> index.html

    - name: "Show the contents of the 'index.html' redirection file"
      shell: bash
      run: |
          cat index.html

    # ------------------------------------------------------------------------

    - uses: pyansys/actions/_logging@main
      with:
        level: "INFO"
        message: >
          Create the '.nojekyll' and 'CNAME' file with the desired values.

    - name: "Create '.nojekyll' and 'CNAME' files"
      shell: bash
      run: |
          touch .nojekyll CNAME
          echo "${{ inputs.cname }}" > CNAME

    # ------------------------------------------------------------------------

    - uses: pyansys/actions/_logging@main
      with:
        level: "INFO"
        message: >
          For deploying the documentation, a GitHub token or a deployment token
          is required. The GitHub token is used when deploying to the current
          repository while the deployment token is used to deploy to an external
          repository.

    - name: "Deploy to ${{ inputs.branch }} branch of ${{ github.repository }} repository"
      if: inputs.repository == 'current'
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_dir: .
        publish_branch: ${{ inputs.branch }}
        github_token: ${{ inputs.token }}
        commit_message: ${{ inputs.commit-message }}
        keep_files: true
        force_orphan: true

    - name: "Deploy to ${{ inputs.branch }} branch of ${{ inputs.repository }}"
      if: inputs.repository != 'current'
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_dir: .
        publish_branch: ${{ inputs.branch }}
        personal_token: ${{ inputs.token }}
        external_repository: ${{ inputs.repository }}
        commit_message: ${{ inputs.commit-message }}
        keep_files: true
        force_orphan: true
