name: "Release to test PyPI index."
description: "Release library artifacts to test PyPI index."

inputs:
  library-name:
    description: 'Name of the Python library.'
    required: true
    type: string
  twine-username:
    description: 'Desired twine user name.'
    required: true
    type: string
  twine-token:
    description: 'Password to be used when uploading to test PyPI.'
    required: true
    type: string
  python-version:
    description: 'Desired Python version for using twine.'
    required: false
    default: '3.10'
    type: string
  download-artifacts:
    description: 'Whether or not download the artifacts. By default download a "``library-name``-artifacts"'
    required: false
    type: bool
    default: true

runs:
  using: "composite"
  steps:
  
    - name: "Release to test PyPI index"
      uses: pyansys/actions/_release-pypi@main
      with:
        library-name: ${{ inputs.library-name }}
        index-name: "https://test.pypi.org/legacy/"
        twine-username: ${{ inputs.twine-username }}
        twine-token: ${{ inputs.twine-token }}
        python-version: ${{ inputs.python-version }}
        download-artifacts: ${{ inputs.download-artifacts }}
