name: "Release to desired PyPI index"
description: "Release library artifacts to PyPI desired index"

inputs:
  library-name:
    description: 'Name of the Python library'
    required: true
    type: string
  index-name:
    description: 'Name of the Python library'
    required: true
    type: string
  twine-username:
    description: 'Desired twine user name'
    required: true
    type: string
  twine-token:
    description: 'Password to be used when uploading to private PyPI'
    required: true
    type: string
  python-version:
    description: 'Desired Python version for using twine'
    required: true
    type: string

runs:
  using: "composite"
  steps:
  
    - name: "Set up Python"
      uses: pyansys/actions/_setup-python@main
      with:
        python-version: ${{ env.MAIN_PYTHON_VERSION }}

    - name: "Install twine"
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install twine

    - name: "Download the library artifacts from build-library step"
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.library-name }}-artifacts
        path: ${{ inputs.library-name }}-artifacts

    - name: "Display the structure of downloaded files"
      shell: bash
      run: ls -R

    - name: "Upload artifacts to private PyPi"
      shell: bash
      run: |
        python -m twine upload --verbose --skip-existing ${{ inputs.library-name }}-artifacts/*.whl
        python -m twine upload --verbose --skip-existing ${{ inputs.library-name }}-artifacts/*.tar.gz
      env:
        TWINE_USERNAME: ${{ inputs.twine-username }}
        TWINE_PASSWORD: ${{ inputs.twine-token }}
        TWINE_REPOSITORY_URL: ${{ inputs.index-name }}
