name: "Release to desired PyPI index"
description: "Release library artifacts to PyPI desired index"

inputs:
  library-name:
    description: 'Name of the Python library'
    required: true
    type: string
  index-name:
    description: 'Name of the Python library'
    required: true
    type: string
  twine-username:
    description: 'Desired twine user name'
    required: true
    type: string
  twine-token:
    description: 'Password to be used when uploading to private PyPI'
    required: true
    type: string
  python-version:
    description: 'Desired Python version for using twine'
    required: true
    type: string
  setup-python:
    description: 'Whether install python or not.'
    required: false
    type: bool
    default: true
  download-artifacts:
    description: 'Whether or not download the artifacts. By default download an artifact named "``library-name``-artifacts"'
    required: false
    type: bool
    default: true


runs:
  using: "composite"
  steps:
  
    - name: "Set up Python"
      if: inputs.setup-python == 'true'
      uses: pyansys/actions/_setup-python@main
      with:
        python-version: ${{ inputs.python-version }}
        use-cache: false

    - name: "Install twine"
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install twine

    - name: "Download the library artifacts from build-library step"
      if: inputs.download-artifacts == 'true'
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.library-name }}-artifacts
        path: ${{ inputs.library-name }}-artifacts

    - name: "Display the structure of downloaded files"
      shell: bash
      run: ls -R

    - name: "Upload artifacts to private PyPi"
      shell: bash
      run: |
        python -m twine upload --verbose --skip-existing ${{ inputs.library-name }}-artifacts/*.whl
        python -m twine upload --verbose --skip-existing ${{ inputs.library-name }}-artifacts/*.tar.gz
      env:
        TWINE_USERNAME: ${{ inputs.twine-username }}
        TWINE_PASSWORD: ${{ inputs.twine-token }}
        TWINE_REPOSITORY_URL: ${{ inputs.index-name }}
