check-environment-approval:
  name: Check environment approval
  runs-on: ubuntu-latest
  outputs:
    environment: ${{ '{{' }} steps.block.outputs.environment {{ '}}' }}
  steps:
    - name: Decide which environment should be used
      id: block
      uses: ansys/actions/check-environment-approval@{{ version }}

check-dependabot-pr:
  needs: [check-environment-approval]
  name: Manual approval (on dependabot PRs)
  runs-on: ubuntu-latest
  environment: ${{ '{{' }} needs.check-environment-approval.outputs.environment {{ '}}' }}
  steps:
    - name: Proceed after approval
      if: ${{ '{{' }} needs.check-environment-approval.outputs.environment == 'dependabot' {{ '}}' }}
      run: |
        echo "::notice::Workflow approved."
    - name: Approval skipped
      if: ${{ '{{' }} needs.check-environment-approval.outputs.environment == '' {{ '}}' }}
      run: |
        echo "::notice::Workflow approval skipped."
