actions-security:
  name: "Check actions security"
  runs-on: ubuntu-latest
  steps:
    - uses: ansys/actions/check-actions-security@{{ version }}
      with:
        generate-summary: true
        token: ${{ '{{ secrets.GITHUB_TOKEN }}' }}
        auditing-level: 'high'
        trust-ansys-actions: true