name: "Check if the branch name follows PyAnsys naming convention."
description: "Action that checks if the name of the branch is following PyAnsys branch naming convention."

runs:
  using: composite

  steps:

    - name: "Get the prefix of the branch"
      env:
        BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 
      if: github.ref_type == 'branch'
      shell: bash
      run: |
        branch_prefix=$(echo "${{ BRANCH_NAME }}" | cut -d '/' -f 1)
        echo "BRANCH_PREFIX=$branch_prefix" >> $
        
    - name: Check branch name has slash
      shell: bash
      env:
        BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 
      if: contains(env.BRANCH_NAME, '/') == false
      uses: pyansys/actions/_logging@main
      with:
        level: "ERROR"
        message: >
          "Branch name ${{ env.BRANCH_NAME }} does not contain a prefix and a backslash."

    - name: Check branch prefix naming
      shell: bash
      if: contains(fromJson('["fix", "feat", "junk", "maint", "doc", "no-ci", "test", "release"]'), env.BRANCH_PREFIX) == false
      uses: pyansys/actions/_logging@main
      with:
        level: "ERROR"
        message: >
          "Branch name ${{ env.BRANCH_PREFIX }} prefix is not valid."
