name: >
  Branch name style

description: >
  Checks if the name of the branch follows the branch naming convention of
  PyAnsys.

runs:
  using: "composite"
  steps:

    - name: "Get the prefix of the branch"
      shell: bash
      if: github.ref_type == 'branch'
      run: |
        branch_name=${{ github.head_ref || github.ref }}
        branch_prefix=$(echo "$branch_name" | cut -d '/' -f 1)
        echo "BRANCH_PREFIX=$branch_prefix" >> $GITHUB_ENV

    - name: "Check if branch has a valid prefix"
      shell: bash
      if: github.ref_type == 'branch'
      run: |
        if [[ ${{ env.BRANCH_NAME }} != */* ]]; then
          echo "\033[1;91m[ERROR]: Branch name ${{ env.BRANCH_NAME }} does not contain a prefix and a backslash." >&2
          exit 1
        fi

        valid_prefixes=("fix" "feat" "junk" "maint" "doc" "no-ci" "test" "release")
        if [[ ! ${valid_prefixes[@]} =~ ${{ env.BRANCH_PREFIX }} ]]; then
          echo "\033[1;91m[ERROR]: Branch name ${{ env.BRANCH_PREFIX }} prefix is not valid." >&2
          exit 1
        fi
