name: >
  Branch name style

description: |
  Checks if the name of the branch follows the branch naming convention of
  PyAnsys.

  .. note::

      Branch names must start with one of the following prefixes:

      - fix
      - feat
      - junk
      - maint
      - docs
      - no-ci
      - testing or test
      - release
      - dependabot

runs:
  using: "composite"
  steps:

    - name: "Check if branch has a valid prefix"
      shell: bash
      if: ${{ (github.ref != 'refs/heads/main') && (github.ref_type == 'branch') }}
      run: |
        branch_name=${{ github.head_ref || github.ref }}

        if [[ $branch_name != */* ]]; then
          echo "\033[1;91m[ERROR]: Branch name $branch_name does not contain a prefix and a backslash." >&2
          exit 1
        fi

        branch_prefix=$(echo "$branch_name" | cut -d '/' -f 1)
        valid_prefixes=("fix" "feat" "junk" "maint" "docs" "no-ci" "test" "testing" "release" "dependabot")

        if [[ ! ${valid_prefixes[@]} =~ $branch_prefix ]]; then
          echo "\033[1;91m[ERROR]: Branch name $branch_prefix prefix is not valid." >&2
          exit 1
        fi
