name: >
  Branch name style

description: >
  Checks if the name of the branch follows the branch naming convention of
  PyAnsys.

runs:
  using: "composite"

  steps:

    - name: "Get the prefix of the branch"
      shell: bash
      if: github.ref_type == 'branch'
      run: |
        branch_name=${{ github.head_ref || github.ref_name }}
        branch_prefix=$(echo "${{ branch_name }}" | cut -d '/' -f 1)
        echo "BRANCH_PREFIX=$branch_prefix" >> $GITHUB_ENV

    - name: "Check if branch has a valid prefix"
      shell: bash
      if: github.ref_type == 'branch'
      run: |

        - name: "Raise and error if branch does not have a prefix"
          uses: pyansys/actions/_logging@main
          if: contains(env.BRANCH_NAME, '/') == false
          with:
            level: "ERROR"
            message: >
              "Branch name ${{ env.BRANCH_NAME }} does not contain a prefix and a backslash."

        - name: "Check branch prefix naming"
          uses: pyansys/actions/_logging@main
          if: !contains(fromJson('["fix", "feat", "junk", "maint", "doc", "no-ci", "test", "release"]'), env.BRANCH_PREFIX)
          with:
            level: "ERROR"
            message: >
              "Branch name ${{ env.BRANCH_PREFIX }} prefix is not valid."
