# Copyright (C) 2022 - 2024 ANSYS, Inc. and/or its affiliates.
# SPDX-License-Identifier: MIT
#
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

name: |
  Release to GitHub action

description: |
    Release library artifacts to the GitHub release section. Some minimum
    artifacts are required before running this action. These artifacts include
    ``documentation-html``, ``documentation-pdf``, and
    ``<library-name>-artifacts`` files. This last file must contain the wheels and
    source distribution files of the library.

    If you are using the ``title_format`` and ``issue_format`` from the ``doc-changelog`` action
    setup guide, https://actions.docs.ansys.com/version/dev/migrations/docs-changelog-setup.html,
    the changelog for your release is included in the release notes on GitHub.


inputs:

  # Required inputs

  library-name:
    description: |
     Name of the Python library to be published.
    required: true
    type: string

  token:
    description: |
      Required password, key or token with the correct credentials for deploying the
      documentation. If deploying to the current repository, the ``secrets.GITHUB_TOKEN`` token is
      is enough. For workflows deploying to other repositories, `generate and
      use a token with writing access
      <https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token>`_
      to that repository.
    required: true
    type: string

  # Optional inputs

  additional-artifacts:
    description: |
        String containing a list of additional artifacts to be included in the
        GitHub release.
    required: false
    default: ''
    type: string

  dry-run:
    description: |
      Whether to run or not this action in testing mode. Testing mode executes
      all the action steps except the releasing artifacts one. This allows
      developers to verify the health of the action once integrated in their
      CI/CD pipelines without actually publishing artifacts. Default value is
      ``false``.
    required: false
    default: false
    type: boolean

  toml-version:
    description: |
      Toml version used for retrieving the towncrier directory.
    default: '0.10.2'
    required: false
    type: string

runs:
  using: "composite"
  steps:

    # TODO: remove this deprecation in ansys/actions@v9

    - uses: ansys/actions/_logging@main
      if: ${{ inputs.token == '' }}
      with:
        level: "ERROR"
        message: >
          Ansys Actions v8 will require the token input in the ``release-github`` action.
          Please add the token input to this action and see
          https://actions.docs.ansys.com/version/dev/migrations/index.html#migration-guide
          for more information.

    # TODO: end

    - name: "Checkout repository"
      uses: actions/checkout@v4

    # ------------------------------------------------------------------------

    - uses: ansys/actions/_logging@main
      with:
        level: "INFO"
        message: >
          Download all artifacts that got generated in the CI/CD. Create a
          directory containing the final artifacts to be published in GitHub.

    - name: "Download all artifacts that got generated in the CI/CD"
      uses: actions/download-artifact@v4
      with:
        path: /tmp/artifacts

    - name: "Generate a distribution folder that will contain the desired artifacts"
      shell: bash
      run: mkdir -p dist

    # ------------------------------------------------------------------------

    - uses: ansys/actions/_logging@main
      with:
        level: "INFO"
        message: >
          Create a dist/documentation directory and move the documentation-html
          artifact and the documentation-pdf artifact inside this folder.
          Finally, compress both artifacts.

    - name: "Moving documentation artifacts to dist/documentation directory"
      shell: bash
      run: |
        mkdir -p dist/documentation
        mv /tmp/artifacts/documentation-html dist/documentation/documentation-html
        mv /tmp/artifacts/documentation-pdf dist/documentation/documentation-pdf

    - name: "Compressing HTML documentation"
      uses: vimtor/action-zip@v1.2
      with:
        files: dist/documentation/documentation-html
        dest: dist/documentation/documentation-html.zip

    - name: "Compressing PDF documentation"
      uses: vimtor/action-zip@v1.2
      with:
        files: dist/documentation/documentation-pdf
        dest: dist/documentation/documentation-pdf.zip

    # ------------------------------------------------------------------------

    - uses: ansys/actions/_logging@main
      with:
        level: "INFO"
        message: >
          Create a dist/wheelhouse directory and move all wheelhouse artifacts
          inside this folder.

    - name: "Move wheelhouse artifacts to dist/wheelhouse directory"
      shell: bash
      run: |
        mkdir -p dist/wheelhouse
        mv /tmp/artifacts/**/*-wheelhouse-*.zip dist/wheelhouse/

    # ------------------------------------------------------------------------

    - uses: ansys/actions/_logging@main
      with:
        level: "INFO"
        message: >
          Create a dist/${{ inputs.library-name }}-artifacts directory and move all wheel artifacts
          inside this folder.

    - name: "Move wheel artifacts to dist/${{ inputs.library-name }}-artifacts directory"
      shell: bash
      run: |
        mv /tmp/artifacts/${{ inputs.library-name }}-artifacts dist/${{ inputs.library-name }}-artifacts

    # ------------------------------------------------------------------------

    - uses: ansys/actions/_logging@main
      if: inputs.additional-artifacts != ''
      with:
        level: "INFO"
        message: >
          Create a dist/extra directory and move all the desired additional
          artifacts inside this directory.

    - name: "Move additional artifacts to dist/wheelhouse directory"
      shell: bash
      if: inputs.additional-artifacts != ''
      run: |
        mkdir -p dist/extra
        for artifact in ${{ inputs.additional-artifacts }}; do
          mv /tmp/artifacts/$artifact dist/extra/$artifact
        done

    # ------------------------------------------------------------------------

    - uses: ansys/actions/_logging@main
      with:
        level: "INFO"
        message: >
          Display the structure of the 'dist/' folder. Upload all artifacts.

    - name: "Display the structure of the 'dist/' folder"
      shell: bash
      run: ls -R dist/

    - name: "Install toml"
      shell: bash
      run: |
        python -m pip install --upgrade pip toml==${{ inputs.toml-version }}

    - name: "Get the release notes body"
      shell: python
      run: |
        import sys
        from pathlib import Path
        sys.path.insert(1, '${{ github.action_path }}/../python-utils/')

        from parse_pr_title import get_towncrier_config_value, save_env_variable
        from release_github_utils import get_tag_section

        # Get the path to your pyproject.toml file
        pyproject_path = Path("${{ github.workspace }}") / "pyproject.toml"

        # Get the path to your changelog file: [tool.towncrier]'s filename configuration
        changelog_loc = get_towncrier_config_value("filename", pyproject_path)
        print(f"CHANGELOG_LOC: {changelog_loc}")

        # Set an empty string for the body of the release notes
        body = ""

        # If the changelog file exists, get the title and content for the release section
        if changelog_loc:
            body = get_tag_section(changelog_loc, body)

        # Save the env variable
        save_env_variable("RELEASE_NOTES_BODY", body)

    - name: "Release to GitHub"
      uses: softprops/action-gh-release@v1
      env:
        REPO_NAME: ${{ github.event.repository.name }}
      if: inputs.dry-run == 'false'
      with:
        fail_on_unmatched_files: false
        generate_release_notes: true
        body: ${{ env.RELEASE_NOTES_BODY }}
        repository: ${{ github.repository_owner }}/${{ env.REPO_NAME }}
        token: ${{ inputs.token }}
        files: |
          # Include wheel and source distribution artifacts
          dist/${{ inputs.library-name }}-artifacts/*.whl
          dist/${{ inputs.library-name }}-artifacts/*.tar.gz

          # Include wheelhouse artifacts
          dist/wheelhouse/**/*-wheelhouse-*.zip

          # Include HTML and PDF documentation artifacts
          dist/documentation/documentation-html.zip
          dist/documentation/documentation-pdf.zip

          # Include additional artifacts
          dist/extra/**/*
