name: "Release to GitHub."
description: "Release library artifacts to GitHub release page."

inputs:
  library-name:
    description: 'Name of the Python library.'
    required: true
    type: string
  download-artifacts:
    description: 'Whether or not download the artifacts.'
    required: false
    type: bool
    default: true


runs:
  using: "composite"
  steps:
  
    - name: "Download the ${{ inputs.library-name }} artifacts from build-library step"
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.library-name }}-artifacts
        path: ${{ inputs.library-name }}-artifacts

    - name: "Download {{ inputs.library-name }} HTML documentation"
      if: inputs.download-artifacts == 'true'
      uses: actions/download-artifact@v3
      with:
        name: documentation-html
        path: documentation-html

    - name: "Zip HTML documentation"
      uses: vimtor/action-zip@v1.1
      with:
        files: documentation-html
        dest: documentation-html.zip

    - name: "Download {{ inputs.library-name }} PDF documentation"
      if: inputs.download-artifacts == 'true'
      uses: actions/download-artifact@v3
      with:
        name: documentation-pdf
        path: documentation-pdf

    - name: "Zip PDF documentation"
      uses: vimtor/action-zip@v1.1
      with:
        files: documentation-pdf
        dest: documentation-pdf.zip

    - name: "Download other artifacts (wheelhouse, cibuildwheel...)"
      if: inputs.download-artifacts == 'true'
      uses: actions/download-artifact@v3
      with:
        path: other-artifacts

    - name: "Remove duplicated artifacts"
      shell: bash
      run: |
        rm -rf other-artifacts/documentation-html
        rm -rf other-artifacts/documentation-pdf
        rm -rf other-artifacts/${{ inputs.library-name }}-artifacts

    - name: "Display the structure of downloaded files"
      shell: bash
      run: ls -R

    - name: "Release to GitHub"
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ${{ inputs.library-name }}/*.whl
          ${{ inputs.library-name }}/*.tar.gz
          documentation-html.zip
          documentation-pdf.zip
          other-artifacts/**/*-wheelhouse-*.zip
