name: >
  Release to GitHub action

description: >
    Release library artifacts to the GitHub release section. Some minimum
    artifacts are required before running this action. These artifacts include
    ``documentation-html``, ``documentation-pdf``, and
    ``<library-name>-artifacts`` files. This last file must contain the wheels and
    source distribution files of the library.

inputs:

  # Required inputs

  library-name:
    description: >
     Name of the Python library to be published.
    required: true
    type: string

  # Optional inputs

  additional-artifacts:
    description: >
        String containing a list of additional artifacts to be included in the
        GitHub release.
    required: false
    default: ''
    type: string

runs:
  using: "composite"
  steps:
  
    - name: "Download the ${{ inputs.library-name }} artifacts from build-library step"
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.library-name }}-artifacts
        path: ${{ inputs.library-name }}-artifacts

    - name: "Download {{ inputs.library-name }} HTML documentation"
      uses: actions/download-artifact@v3
      with:
        name: documentation-html
        path: documentation-html

    - name: "Zip HTML documentation"
      uses: vimtor/action-zip@v1.1
      with:
        files: documentation-html
        dest: documentation-html.zip

    - name: "Download {{ inputs.library-name }} PDF documentation"
      uses: actions/download-artifact@v3
      with:
        name: documentation-pdf
        path: documentation-pdf

    - name: "Zip PDF documentation"
      uses: vimtor/action-zip@v1.1
      with:
        files: documentation-pdf
        dest: documentation-pdf.zip

    - name: "Download all artifacts that got generated in the CI/CD"
      uses: actions/download-artifact@v3
      with:
        path: all-artifacts

    - name: "Isolate wheelhouse artifacts"
      shell: bash
      run: |
        mkdir -p wheelhouse
        mv all-artifacts/**/*-wheelhouse-*.zip wheelhouse/

    - name: "Remove undesired artifacts"
      shell: bash
      run: |
        mkdir 
        rm -rf other-artifacts/documentation-html
        rm -rf other-artifacts/documentation-pdf
        rm -rf other-artifacts/${{ inputs.library-name }}-artifacts

    - name: "Display the structure of downloaded files"
      shell: bash
      run: ls -R

    - name: "Release to GitHub"
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ${{ inputs.library-name }}-artifacts/*.whl
          ${{ inputs.library-name }}-artifacts/*.tar.gz
          documentation-html.zip
          documentation-pdf.zip
