# Copyright (C) 2022 - 2024 ANSYS, Inc. and/or its affiliates.
# SPDX-License-Identifier: MIT
#
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

name: |
  Utils logging action

description: |
  This action is used to generate logging messages during the execution of other
  actions. It supports three logging levels including ``ERROR``, ``WARNING``,
  and ``INFO``. ANSI colors are used to report the different levels. This allows
  to quickly identify those in the GitHub actions logs.

inputs:

  # Required inputs

  level:
    description: |
      Logging level of the message. Supported levels are ``ERROR``, ``WARNING``
      and ``INFO``.
    required: true
    type: string

  message:
    description: |
      The message to save in the logging report.
    required: true
    type: string

runs:
  using: "composite"
  steps:

    # -------------------------------- Linux ---------------------------------

    - name: "Report error message"
      shell: bash
      if: ${{ inputs.level == 'ERROR' && runner.os == 'Linux' }}
      run: |
        echo -e "\033[1;91m[ERROR]: ${{ inputs.message }}\033[0m"
        exit 1

    - name: "Report warning message"
      shell: bash
      if: ${{ inputs.level == 'WARNING' && runner.os == 'Linux' }}
      run: |
        echo -e "\033[1;93m[WARNING]: ${{ inputs.message }}\033[0m"

    - name: "Report info message"
      shell: bash
      if: ${{ inputs.level == 'INFO' && runner.os == 'Linux' }}
      run: |
        echo -e "\033[1;92m[INFO]: ${{ inputs.message }}\033[0m"

    # ------------------------------- Windows --------------------------------

    - name: "Report error message"
      shell: powershell
      if: ${{ inputs.level == 'ERROR' && runner.os == 'Windows' }}
      run: |
        Write-Host "$([char]27)[91m[ERROR]: ${{ inputs.message }}$([char]27)[0m"
        Exit 1

    - name: "Report warning message"
      shell: powershell
      if: ${{ inputs.level == 'WARNING' && runner.os == 'Windows' }}
      run: |
        Write-Host "$([char]27)[93m[WARNING]: ${{ inputs.message }}$([char]27)[0m"

    - name: "Report info message"
      shell: powershell
      if: ${{ inputs.level == 'INFO' && runner.os == 'Windows' }}
      run: |
        Write-Host "$([char]27)[92m[INFO]: ${{ inputs.message }}$([char]27)[0m"
