# Copyright (C) 2022 - 2024 ANSYS, Inc. and/or its affiliates.
# SPDX-License-Identifier: MIT
#
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

name: |
  Release to PyPI private index action

description: |
  Release library artifacts to the PyAnsys private index. Use the
  ``PYANSYS_PRIVATE_PYPI_TOKEN`` as the token. Artifacts get downloaded from the
  CI/CD pipeline and are assumed to be named ``<library-name>-artifacts``. This
  file is expected to contain a wheel and a source distribution file for the
  desired library.

inputs:

  # Required inputs

  library-name:
    description: |
      Name of the Python library to be published.
    required: true
    type: string

  # Optional inputs

  twine-username:
    description: |
      User name used when uploading to the PyAnsys private index.
    required: false
    default: '__token__'
    type: string

  twine-token:
    description: |
      Password used when uploading to the PyAnsys private index.
    required: false
    default: ''
    type: string

  use-trusted-publisher:
    description: |
      Whether to use the OIDC token for releasing. Default value is ``false``.
      This is useful when you want to publish to PyPI through a CI/CD pipeline
      as a Trusted Publisher. It is necessary that your repository has been authorized
      to use Trusted Publisher's. For more information, see
      `Using a Trusted Publisher <https://docs.pypi.org/trusted-publishers/>`_.

      .. note::

          ``permissions: id-token: write`` is mandatory for trusted publishing.

    required: false
    default: false
    type: boolean

  dry-run:
    description: |
      Whether to run or not this action in testing mode. Testing mode executes
      all the action steps except the releasing artifacts one. This allows
      developers to verify the health of the action once integrated in their
      CI/CD pipelines without actually publishing artifacts. Default value is
      ``false``.
    required: false
    default: false
    type: boolean

  skip-existing:
    description: |
      Continue uploading files if one already exists. Only valid when uploading
      to PyPI. Other implementations may not support this.
    required: false
    default: true
    type: boolean

  python-version:
    description: |
      Python version for installing and using `twine
      <https://twine.readthedocs.io/en/stable/>`_.
    required: false
    default: '3.10'
    type: string

  index-name:
    description: |
      The name of the index endpoint used for uploading the artifacts.
    required: true
    default: "https://pkgs.dev.azure.com/pyansys/_packaging/pyansys/pypi/upload"
    type: string

runs:
  using: "composite"
  steps:

    - name: "Release to PyAnsys private index"
      uses: ansys/actions/_release-pypi@main
      with:
        library-name: ${{ inputs.library-name }}
        index-name: ${{ inputs.index-name }}
        twine-username: ${{ inputs.twine-username }}
        twine-token: ${{ inputs.twine-token }}
        python-version: ${{ inputs.python-version }}
        dry-run: ${{ inputs.dry-run }}
        skip-existing: ${{ inputs.skip-existing }}
        use-trusted-publisher: ${{ inputs.use-trusted-publisher }}
