name: >
  Release to PyPI private index action

description: >
  Release library artifacts to the PyAnsys private index. Use the
  ``PYANSYS_PRIVATE_PYPI_TOKEN`` as token. Artifacts get downloaded from the
  CI/CD pipeline and are assumed to be named ``<library-name>-artifacts``. This
  file is expected to contain a wheel and a source distribution file for the
  desired library.

inputs:

  # Required inputs

  library-name:
    description: >
      Name of the Python library to be published.
    required: true
    type: string

  twine-username:
    description: >
      User named used when uploading to the PyAnsys private index.
    required: true
    type: string

  twine-token:
    description: >
      Password used when uploading to the PyAnsys private index.
    required: true
    type: string

  # Optional inputs

  python-version:
    description: >
      Python version for installing and using `twine
      <https://twine.readthedocs.io/en/stable/>`_.
    required: false
    default: '3.10'
    type: string

runs:
  using: "composite"
  steps:
  
    - name: "Release to PyAnsys private index"
      uses: pyansys/actions/_release-pypi@main
      with:
        library-name: ${{ inputs.library-name }}
        index-name: "https://pkgs.dev.azure.com/pyansys/_packaging/pyansys/pypi/upload"
        twine-username: ${{ inputs.twine-username }}
        twine-token: ${{ inputs.twine-token }}
        python-version: ${{ inputs.python-version }}
