name: >
  Documentation Changelog

description: |
  Adds a newsfragment to the target repository using ``towncrier``
  containing the title and number of the pull request.

inputs:

  # Required inputs

  token:
    description: >
      GitHub token for doing a git commit & push
    required: true
    type: string

  # Optional inputs

  python-version:
    description: >
      Python version used for setting up Python.
    default: '3.10'
    required: false
    type: string

  use-python-cache:
    description: >
      Whether to use the Python cache for installing previously downloaded
      libraries. If ``true``, previously downloaded libraries are installed from the
      Python cache. If ``false``, libraries are downloaded from the PyPI index.
    required: false
    default: true
    type: boolean

runs:
  using: "composite"
  steps:
    - name: "Install Git and clone project"
      env:
        PR_BRANCH: ${{ github.event.pull_request.head.ref }}
      uses: actions/checkout@v4
      with:
        # Required to checkout branch from origin rather than remote
        ref: ${{ env.PR_BRANCH }}

    - name: "Set up Python ${{ inputs.python-version }}"
      env:
        PYTHON_VERSION: ${{ inputs.python-version }}
        PYTHON_CACHE: ${{ inputs.use-python-cache }}
      uses: ansys/actions/_setup-python@main
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        use-cache: ${{ env.PYTHON_CACHE }}

    - name: "Install towncrier"
      shell: bash
      run: |
        python -m pip install --upgrade pip towncrier

    - name: "Set PR_TYPE env variable based on PR label"
      shell: python
      run: |
        pr_labels = {
          "enhancement": "added",
          "bug": "fixed",
          "dependencies": "dependencies",
          "documentation": "documentation",
          "maintenence": "changed"
        }

        existing_labels = ${{ toJSON(github.event.pull_request.labels.*.name) }}

        def get_changelog_section(pr_labels, existing_labels):
          label_type = ""

          for key, value in pr_labels.items():
              if key in existing_labels:
                  label_type = value
                  return label_type

          label_type = "miscellaneous"
          return label_type

        print(PR_TYPE=get_changelog_section(pr_labels, existing_labels)) >> $GITHUB_ENV

    - name: "Create and commit towncrier fragment"
      if: ${{ env.PR_TYPE }} != ""
      env:
        PR_BRANCH: ${{ github.event.pull_request.head.ref }}
        PR_TITLE: "${{ github.event.pull_request.title }}"
        PR_NUMBER: ${{ github.event.number }}
      shell: bash
      run: |
        fragment="${{ env.PR_NUMBER }}.${{ env.PR_TYPE }}.md"

        # Check if the fragment file exists in the repository
        exists=`find . -type f -name "$fragment"`
        # If the file exists, remove it
        if [ ! -z "$exists" ]; then rm $exists; fi

        # Create changelog fragment with towncrier
        towncrier create -c "${{ env.PR_TITLE }}" $fragment

        # Configure git username & email
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'

        # Add towncrier fragment
        git add .

        modified=`git diff HEAD --name-only`
        echo "modified: $modified"

        if [ ! -z "$modified" ]; then
          # Commit and push fragment
          git commit -m "adding fragment"
          git push
        fi