name: >
  Documentation Changelog

description: |
  Adds a newsfragment to the target repository using ``towncrier``
  containing the title and number of the pull request.

inputs:

  token:
    description: >
      GitHub token for doing a git commit & push
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: "Install Git and clone project"
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.pr-branch }}

    - name: "Set up Python ${{ inputs.python-version }}"
      uses: ansys/actions/_setup-python@main
      with:
        python-version: ${{ inputs.python-version }}
        use-cache: ${{ inputs.use-python-cache }}

    - name: "Install towncrier"
      shell: bash
      run: |
        python -m pip install --upgrade pip towncrier

    - name: "Check pull request type"
      env:
        PR_TITLE: "${{ github.event.pull_request.title }}"
      shell: bash
      run: |
        # Check if PR_TITLE string contains Add, Remove, Change, Fix, or Bump
        if [[ "${{ env.PR_TITLE }}" =~ [a,A]dd ]]; then echo "PR_TYPE=added" >> $GITHUB_ENV;
        elif [[ "${{ env.PR_TITLE }}" =~ [r,R]emove ]]; then echo "PR_TYPE=removed" >> $GITHUB_ENV;
        elif [[ "${{ env.PR_TITLE }}" =~ [c,C]hange ]]; then echo "PR_TYPE=changed" >> $GITHUB_ENV;
        elif [[ "${{ env.PR_TITLE }}" =~ [f,F]ix ]]; then echo "PR_TYPE=fixed" >> $GITHUB_ENV;
        elif [[ "${{ env.PR_TITLE }}" =~ [b,B]ump ]]; then echo "PR_TYPE=dependencies" >> $GITHUB_ENV;
        else
          echo "The pull request title "${{ env.PR_TITLE }}" is invalid. Please ensure it contains one of the following keywords:"
          echo  "Add, Remove, Change, Fix, or Bump (for dependencies)."
          exit 1
        fi

    - name: "Create and commit towncrier fragment"
      env:
        PR_BRANCH: ${{ github.event.pull_request.head.ref }}
        PR_TITLE: "${{ github.event.pull_request.title }}"
        PR_NUMBER: ${{ github.event.number }}
      shell: bash
      run: |
        fragment="${{ env.PR_NUMBER }}.${{ env.PR_TYPE }}.md"
        pr_type_arr=("added" "removed" "changed" "fixed" "dependencies")

        # Remove fragment if it already exists for pull request
        for type in "${pr_type_arr[@]}"
        do
          exists=`find . -type f -name "${{ env.PR_NUMBER }}.$type.md"`
          if [ ! -z "$exists" ]; then rm $exists; fi
        done

        # Create changelog fragment with towncrier
        towncrier create -c "${{ env.PR_TITLE }}" $fragment

        # Configure git username & email
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'

        modified=`git diff HEAD --name-only`
        echo "modified: $modified"

        if [ ! -z "$modified" ]; then
          # Add and commit fragment
          git add .
          git commit -m "adding fragment"
          git push
        fi