# Copyright (C) 2022 - 2024 ANSYS, Inc. and/or its affiliates.
# SPDX-License-Identifier: MIT
#
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

name: |
  Documentation Changelog

description: |
  Adds a newsfragment to the target repository using ``towncrier``
  containing the title and number of the pull request.

  This action will only work on Linux/macOS runners.

inputs:
  # Required inputs

  token:
    description: |
      Use the PYANSYS_CI_BOT_TOKEN to do a git commit & push.
      The "contents: write" and "pull-requests: write" permissions
      are required for this action.
    required: true
    type: string

  bot-user:
    description: |
      Use the PYANSYS_CI_BOT_USERNAME as the user for a git commit & push.
    required: true
    type: string

  bot-email:
    description: |
      Use the PYANSYS_CI_BOT_EMAIL as the email for a git commit & push.
    required: true
    type: string

  # Optional inputs

  python-version:
    description: |
      Python version used for setting up Python.
    default: '3.10'
    required: false
    type: string

  towncrier-version:
    description: |
      Towncrier version used for creating fragment files.
    default: '23.11.0'
    required: false
    type: string

  toml-version:
    description: |
      Toml version used for retrieving the towncrier directory.
    default: '0.10.2'
    required: false
    type: string

  use-python-cache:
    description: |
      Whether to use the Python cache for installing previously downloaded
      libraries. If ``true``, previously downloaded libraries are installed from the
      Python cache. If ``false``, libraries are downloaded from the PyPI index.
    required: false
    default: true
    type: boolean

  use-conventional-commits:
    description: |
      Use conventional commits to cateogrize towncrier fragments.
    required: false
    default: false
    type: boolean

  use-default-towncrier-config:
    description: |
      Use the default towncrier configuration in the pyproject.toml file.
    required: false
    default: false
    type: boolean

runs:
  using: "composite"
  steps:
    - name: "Install Git and clone project"
      env:
        PR_BRANCH: ${{ github.event.pull_request.head.ref }}
      uses: actions/checkout@v4
      with:
        # Required to checkout branch from origin rather than remote
        ref: ${{ env.PR_BRANCH }}
        token: ${{ inputs.token }}

    - name: "Set up Python ${{ inputs.python-version }}"
      uses: ansys/actions/_setup-python@main
      with:
        python-version: ${{ inputs.python-version }}
        use-cache: ${{ inputs.use-python-cache }}

    - name: "Install towncrier"
      shell: bash
      run: |
        python -m pip install --upgrade pip towncrier==${{ inputs.towncrier-version }} toml==${{ inputs.toml-version }}

    # TODO: remove this deprecation in ansys/actions@v9

    - uses: ansys/actions/_logging@main
      if: ${{ (inputs.bot-user == '') || (inputs.bot-email == '') }}
      with:
        level: "ERROR"
        message: >
          Ansys Actions v8 will require bot username and email inputs in the
          ``doc-changelog``, ``doc-deploy-changelog``, ``doc-deploy-dev`` and
          ``doc-deploy-stable`` actions. Please add the bot-user and bot-email inputs
          to the respective workflows and see
          https://actions.docs.ansys.com/version/dev/migrations/index.html#migration-guide
          for more information.

    # TODO: end

    - name: Check double quotes
      env:
        PR_TITLE: ${{ github.event.pull_request.title }}
      shell: python
      run: |
        import sys
        sys.path.insert(1, '${{ github.action_path }}/../python-utils/')

        from parse_pr_title import save_env_variable

        myvar = """${{ github.event.pull_request.title }}"""
        save_env_variable("QUOTE_TYPE", "double")
      continue-on-error: true

    - name: Check single quotes
      env:
        PR_TITLE: ${{ github.event.pull_request.title }}
      shell: python
      run: |
        import sys
        sys.path.insert(1, '${{ github.action_path }}/../python-utils/')

        from parse_pr_title import save_env_variable

        myvar = '''${{ github.event.pull_request.title }}'''
        save_env_variable("QUOTE_TYPE", "single")
      continue-on-error: true

    - name: "Get first letter of conventional commit type"
      if: ${{ inputs.use-conventional-commits == 'true' }}
      env:
        PR_TITLE: ${{ github.event.pull_request.title }}
      shell: python
      run: |
        import sys
        sys.path.insert(1, '${{ github.action_path }}/../python-utils/')

        from parse_pr_title import get_first_letter_case, get_pr_title_with_quotes

        pr_title = get_pr_title_with_quotes(${{ env.QUOTE_TYPE }})
        get_first_letter_case(pr_title)

    - name: "Check pull-request title follows conventional commits style"
      if: ${{ (inputs.use-conventional-commits == 'true') && (env.FIRST_LETTER == 'lowercase') }}
      uses: ansys/actions/check-pr-title@v8
      with:
        token: ${{ inputs.token }}

    - name: "Check pull-request title follows conventional commits style with upper case"
      if: ${{ (inputs.use-conventional-commits == 'true') && (env.FIRST_LETTER == 'uppercase') }}
      uses: ansys/actions/check-pr-title@v8
      with:
        token: ${{ inputs.token }}
        use-upper-case: true

    - name: "Get conventional commit type from title"
      if: ${{ inputs.use-conventional-commits == 'true' }}
      env:
        PR_TITLE: "${{ github.event.pull_request.title }}"
      shell: python
      run: |
        import sys
        sys.path.insert(1, '${{ github.action_path }}/../python-utils/')

        from parse_pr_title import get_conventional_commit_type, get_pr_title_with_quotes

        pr_title = get_pr_title_with_quotes(${{ env.QUOTE_TYPE }})
        get_conventional_commit_type(pr_title)

    - name: "Get labels in the pull request"
      if: ${{ inputs.use-conventional-commits == 'false' }}
      env:
        GH_TOKEN: ${{ inputs.token }}
        REPO_NAME: ${{ github.event.repository.name }}
      shell: bash
      run: |
        # Get the labels in the pull request
        pr_labels=$(gh api repos/${{ github.repository_owner }}/${{ env.REPO_NAME }}/pulls/${{ github.event.number }} --jq '.labels.[].name')

        # Save the labels to an environment variable
        # For example, LABELS="enhancement maintenance"
        echo LABELS='"'$pr_labels'"' >> $GITHUB_ENV

    - name: "Set CHANGELOG category based on conventional commit type"
      if: ${{ inputs.use-conventional-commits == 'true' }}
      shell: python
      run: |
        import sys
        sys.path.insert(1, '${{ github.action_path }}/../python-utils/')

        from parse_pr_title import changelog_category_cc

        cc_type = ${{ env.CC_TYPE }}
        changelog_category_cc(cc_type)

    - name: "Set PR label environment variable"
      if: ${{ inputs.use-conventional-commits == 'false' }}
      shell: python
      run: |
        import sys
        sys.path.insert(1, '${{ github.action_path }}/../python-utils/')

        from parse_pr_title import changelog_cateogry_labels

        labels = ${{ env.LABELS }}
        changelog_cateogry_labels(labels)

    - name: "Remove PR fragment file if it already exists"
      shell: bash
      run: |
        # Find files containing the PR number
        # For example, 20.*.md
        file=`find . -type f -name "${{ github.event.number }}.*.md"`

        # If the fragment file exists, then delete the file
        if [ ! -z "$file" ]; then
          echo "Removing $file"
          rm $file
        fi

    - name: "Clean PR title"
      env:
        PR_TITLE: ${{ github.event.pull_request.title }}
      shell: python
      run: |
        import sys
        sys.path.insert(1, '${{ github.action_path }}/../python-utils/')

        from parse_pr_title import clean_pr_title, get_pr_title_with_quotes

        pr_title = get_pr_title_with_quotes(${{ env.QUOTE_TYPE }})
        use_cc = True if "${{ inputs.use-conventional-commits }}" == "true" else False

        clean_pr_title(pr_title, use_cc)

    - name: "Append towncrier categories to pyproject.toml"
      env:
        REPO_NAME: ${{ github.event.repository.name }}
      shell: python
      run: |
        import sys
        sys.path.insert(1, '${{ github.action_path }}/../python-utils/')

        from parse_pr_title import add_towncrier_config

        repo_name = "${{ env.REPO_NAME }}"
        org_name = "${{ github.repository_owner }}"

        default_config = True if "${{ inputs.use-default-towncrier-config }}" == "true" else False

        add_towncrier_config(org_name, repo_name, default_config)

    - name: "Create and commit towncrier fragment"
      shell: bash
      run: |
        # Changelog fragment file in the following format
        # For example, 20.added.md
        fragment="${{ github.event.number }}.${{ env.CHANGELOG_SECTION }}.md"

        # Create changelog fragment with towncrier
        # Fragment file contains the title of the PR
        towncrier create -c "${{ env.CLEAN_TITLE }}" $fragment

        # Configure git username & email
        git config user.name ${{ inputs.bot-user }}
        git config user.email ${{ inputs.bot-email }}

        # Add towncrier fragment
        git add .

        # Check if file was modified
        modified=`git diff HEAD --name-only`

        # If the file was modified, commit & push it to the branch
        if [ ! -z "$modified" ]; then
          echo "modified: $modified"
          # Commit and push fragment
          git commit -m "chore: adding changelog file $fragment [dependabot-skip]"
          git push
        fi
