name: >
  Lint Dockerfile

description: >
  This action evaluates the quality of your project Dockerfile(s) by using `hadolint
  <https://github.com/hadolint/hadolint/>`_. The action uses `hadolint-action
  <https://github.com/hadolint/hadolint-action>`_ behind the scenes. Multiple
  Dockerfiles can be linted if the project uses a folder structure where every
  Dockerfile is contained inside its own directory, e.g. docker/windows/Dockerfile and
  docker/linux/Dockerfile.
  
  .. warning::

      This action works only if each directory contains exactly one Dockerfile, otherwise
      it will not work as expected.

inputs:

  # Optional inputs

  working_directories:
    description: >
      A comma-separated list of directories from which to search for Dockerfile(s).
    required: false
    default: "docker"

  recursive:
    description: >
      Search for Dockerfile(s) recursively.
    required: false
    default: false

runs:
  using: "composite"
  steps:

    - name: "Install Git and clone project"
      uses: actions/checkout@v4

    - name: Check working directories
      run: |
        IFS=',' read -ra dirs <<< "${{ inputs.working_directories }}"
        for dir in "${dirs[@]}"; do
          if [ ! -d "$dir" ]; then
            echo "Directory $dir does not exist !"
            exit 1
          fi
        done
        echo "All directories exist"

    - name: Run Hadolint
      uses: hadolint/hadolint-action@v3.1.0
      env:
        HADOLINT_RECURSIVE: "${{ inputs.recursive }}"
      with:
        dockerfile: "Dockerfile"
        recursive: ${{ inputs.recursive }}