# Copyright (C) 2022 - 2025 ANSYS, Inc. and/or its affiliates.
# SPDX-License-Identifier: MIT
#
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

name: |
  Build CI wheels

description: |
  Build wheels for a Python library containing compiled source code. This action
  is expected to be used within a matrix job. Its goal is to generate wheel
  files for every combination of operating system, build system, and Python
  version. The action uses the `cibuildwheel
  <https://github.com/pypa/cibuildwheel>`_ behind the scenes.

  .. note::

      This actions should only be used by libraries including source code that
      needs to be compiled.

inputs:

  # Required inputs

  python-version:
    description: |
      Python version used for building the wheels.
    required: true
    type: string

  library-name:
    description: |
      Name of the Python library. This is the name used when uploading the wheel
      and source distribution as artifacts. The name should be the same one used
      in the PyPI index.
    required: true
    type: string

  operating-system:
    description: |
      Name of the operating system where the library is installed.
    required: true
    type: string

  # Optional inputs

  cibw-build:
    description: |
      Desired build wheel CPython version.
    default: 'cp310-*'
    required: false
    type: string

  cibw-archs:
    description: |
      Desired build architecture.
    default: "auto"
    required: false
    type: string

  requires-pypy:
      description: |
        Whether to generate wheels for wheel files for `PyPy
        <https://www.pypy.org/>`_ in addition to the wheel files for CPython.
        Default value is ``false``.
      default: false
      required: false
      type: boolean

runs:
  using: "composite"
  steps:

    - name: "Install Git and clone project"
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: "Set up QEMU"
      if: ${{ inputs.cibw-archs == 'aarch64' }}
      uses: docker/setup-qemu-action@2b82ce82d56a2a04d2637cd93a637ae1b359c0a7 # v2.2.0
      with:
        platforms: arm64

    - name: "Build wheels for CPython ${{ inputs.python-version }}"
      if: ${{ inputs.requires-pypy == 'false' }}
      uses: pypa/cibuildwheel@ee63bf16da6cddfb925f542f2c7b59ad50e93969 # v2.22.0
      env:
        CIBW_BUILD: ${{ inputs.cibw-build }}
        CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
        CIBW_MANYLINUX_I686_IMAGE: manylinux2014
        CIBW_ARCHS: ${{ inputs.cibw-archs }}

    - name: "Build wheels for PyPy"
      if: ${{ inputs.requires-pypy == 'true' && inputs.cibw-archs != 'aarch64' }}
      uses: pypa/cibuildwheel@ee63bf16da6cddfb925f542f2c7b59ad50e93969 # v2.22.0
      env:
        CIBW_BUILD: "pp39-*"
        CIBW_SKIP: ${{ inputs.cibw-skip }}
        CIBW_ARCHS: ${{ inputs.cibw-archs }}

    - name: "Upload wheel"
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: ${{ inputs.library-name }}-${{ inputs.operating-system }}-${{ inputs.python-version }}-wheels
        path: ./wheelhouse/*.whl
        retention-days: 7
