name: >
  Build CI wheels

description: |
  Build wheels for a Python library containing compiled source code. This action
  is expected to be used within a matrix job. Its goal is to generate wheel
  files for every combination of operating system, build system, and Python
  version. The action uses the `cibuildwheel
  <https://github.com/pypa/cibuildwheel>`_ behind the scenes.

  .. note::

      This actions should only be used by libraries including source code that
      needs to be compiled.

inputs:

  # Required inputs

  python-version:
    description: >
      Python version used for building the wheels.
    required: true
    type: string

  # Optional inputs

  cibw-build:
    description: >
      Desired build wheel CPython version.
    default: 'cp310-*'
    required: false
    type: string

  cibw-skip:
    description: >
      Desired conditions to skip when building the wheels.
    default: "*-musllinux*"
    required: false
    type: string

  cibw-archs:
    description: >
      Desired build architecture.
    default: "auto"
    required: false
    type: string

  requires-pypy:
      description: >
        Whether to generate wheels for wheel files for `PyPy
        <https://www.pypy.org/>`_ in addition to the wheel files for CPython.
        Default value is ``false``.
      default: false
      required: false
      type: boolean

runs:
  using: "composite"
  steps:

    - name: "Install Git and clone project"
      uses: actions/checkout@v4

    - name: "Set up QEMU"
      if: ${{ inputs.cibw-archs == 'aarch64' }}
      uses: docker/setup-qemu-action@v2
      with:
        platforms: arm64

    - name: "Build wheels for CPython ${{ inputs.python-version }}"
      if: ${{ inputs.cibw-build  != 'cp38-*' && inputs.requires-pypy == 'false' }}
      uses: pypa/cibuildwheel@v2.11.1
      env:
        CIBW_BUILD: ${{ inputs.cibw-build }}
        CIBW_SKIP: ${{ inputs.cibw-skip }}
        CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
        CIBW_MANYLINUX_I686_IMAGE: manylinux2014
        CIBW_ARCHS: ${{ inputs.cibw-archs }}

    - name: "Build wheels for CPython 3.8"
      if: ${{ inputs.cibw-build == 'cp38-*' && inputs.requires-pypy == 'false' }}
      uses: pypa/cibuildwheel@v2.11.1
      env:
        CIBW_BUILD: ${{ inputs.cibw-build }}
        CIBW_SKIP: ${{ inputs.cibw-skip }}
        CIBW_MANYLINUX_X86_64_IMAGE: manylinux2010
        CIBW_MANYLINUX_I686_IMAGE: manylinux2010
        CIBW_ARCHS: ${{ inputs.cibw-archs }}

    - name: "Build wheels for PyPy"
      if: ${{ inputs.requires-pypy == 'true' && inputs.cibw-archs != 'aarch64' }}
      uses: pypa/cibuildwheel@v2.11.1
      env:
        CIBW_BUILD: "pp38-* pp39-*"
        CIBW_SKIP: ${{ inputs.cibw-skip }}
        CIBW_ARCHS: ${{ inputs.cibw-archs }}

    - name: "Upload wheel"
      uses: actions/upload-artifact@v3
      with:
        name: wheels
        path: ./wheelhouse/*.whl
        retention-days: 7
