name: >
  Doc deploy dev index action

description: |
  This action automates the process of creating indexes and scraping the
  desired HTML documentation artifact that contains the development version
  of a library, then deploying it to a Meilisearch instance.

inputs:

  # Required inputs

  cname:
    description: >
      The Canonical Name (CNAME) that points to the documentation website.
    required: true
    type: string

  library-name:
    description: >
      The name of the library.
    required: true
    type: string

  api-key:
    description: >
      The API key used to access the Meilsearch instance host.
    required: true
    type: string

  host-url:
    description: >
      The URL where the Meilsearch instance is hosted.
    required: true
    type: string

  # Optional inputs

  doc-artifact-name:
    description: >
      The name of the HTML documentation artifact. This artifact is expected to
      contain all the HTML and static files.The dafault value is ``documentation-html``.
    required: false
    default: 'documentation-html'
    type: string

  template:
    description: >
      The "template" parameter specifies the layout used for the HTML documentation.
      By default, it is set to ``sphinx_pydata`` which assumes that the document is
      constructed using the pydata-sphinx-theme or its associated theme,
      such as the ansys-sphinx-theme.
    required: false
    default: "sphinx_pydata"
    type: string



runs:
  using: "composite"
  steps:

    # ------------------------------------------------------------------------

    - uses: ansys/actions/_logging@main
      with:
        level: "INFO"
        message: >
          Checkout the repository branch for deploying the documentation. If
          this step fails, then it means that the provided token is not valid.

    - name: "Get the name of the repository"
      shell: bash
      run: |
        if [[ "${{ inputs.repository }}" == "current" ]]; then
          echo "REPOSITORY=${{ github.repository }}" >> $GITHUB_ENV
        else
          echo "REPOSITORY=${{ inputs.repository }}" >> $GITHUB_ENV
        fi

    - name: "Checkout ${{ env.REPOSITORY }} repository"
      uses: actions/checkout@v3
      with:
        repository: ${{ env.REPOSITORY }}
        ref: ${{ inputs.branch }}
        token: ${{ inputs.token }}

    # ------------------------------------------------------------------------

    - uses: ansys/actions/_logging@main
      with:
        level: "INFO"
        message: >
          Download the documentation artifact from the current workflow.

    - name: "Download the development documentation artifact"
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.doc-artifact-name }}
        path: ${{ inputs.doc-artifact-name }}

    - name: "Display structure of version/dev"
      shell: bash
      run: |
        ls -R version/dev

    # ------------------------------------------------------------------------

    - uses: ansys/actions/_logging@main
      with:
        level: "INFO"
        message: >
          Install the pymeilisearch required for the indexing.

    - name: "Install build and twine"
      shell: bash
      run: |
        python -m pip install pymeilisearch

     # ------------------------------------------------------------------------

    - uses: ansys/actions/_logging@main
      with:
        level: "INFO"
        message: >
          Scrap the document and deploy it to pymeilisearch.

    - name: Scrape the dev documentation to meilisearch
      shell: bash
      run: |
        pymeilisearch upload --template ${{ inputs.template }} --index ${{ inputs.library_name }}-vdev  --cname ${{ inputs.cname }}/version/dev/ html ${{ inputs.doc-artifact-name }}
      env:
        MEILISEARCH_HOST_URL: ${{ inputs.host-url }}
        MEILISEARCH_API_KEY: ${{ inputs.api-key }}