# Copyright (C) 2022 - 2024 ANSYS, Inc. and/or its affiliates.
# SPDX-License-Identifier: MIT
#
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

name: >
  Generate a robots.txt file for a website.

description: |
  This process creates a ``robots.txt`` file, which enhances the search
  engine's browsing experience of our documentation. The process is a private
  composite action that is executed as a component of the PyAnsys documentation
  deployment strategies.

inputs:

  # Required inputs

  cname:
    description: >
      The canonical name (CNAME) containing the documentation.
    required: true
    type: string

runs:
  using: "composite"
  steps:

    # ------------------------------------------------------------------------

    - uses: ansys/actions/_logging@main
      with:
        level: "INFO"
        message: >
          Generating the "robots.txt" file.

    - name: "Generate the robots.txt file"
      shell: bash
      run: |
        rm robots.txt && touch robots.txt

    - name: "Allow all agents to crawl the website"
      shell: bash
      run: |
        echo "User-agent: *\n" > robots.txt

    - name: "Iterate over all versions except the "
      shell:
      run: |
        for version in $(ls version |
                    grep -E "^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(\..*)?$" | \
                    sort -r --version-sort | \
                    # Do not include the first version
                    tail -n +2); do
            echo "Disallow: /version/${version}" >> robots.txt
        done

    - name: "Include the location of the sitemap.xml file"
      shell: bash
      run: |
        echo "\nSitemap: https://${{ inputs.cname }}/sitemap.xml" >> robots.txt
