name: >
  Code style

description: >
  This action evaluates the code quality of your project by using `pre-commit
  <https://github.com/pre-commit/pre-commit/>`_. The action installs and runs
  ``pre-commit``. It is assumed that your project contains a
  ``.pre-commit-config.yaml`` file in the root directory.

inputs:

  # Optional inputs

  python-version:
    description: >
      Python version used for installing and running ``pre-commit``.
    default: '3.10'
    required: false
    type: string

  use-python-cache:
    description: >
      Whether to use the Python cache for installing previously downloaded
      libraries. If ``true``, previously downloaded libraries are installed from the
      Python cache. If ``false``, libraries are downloaded from the PyPI index.
    required: false
    default: true
    type: boolean

  docker-directory:
    description: >
      A comma-separated list of directories from which to search for Dockerfile(s).
    required: false
    default: "docker"

  docker-recursive:
    description: >
      Search for Dockerfile(s) recursively.
    required: false
    default: false

runs:
  using: "composite"
  steps:

    - name: "Install Git and clone project"
      uses: actions/checkout@v4

    - name: "Set up Python"
      uses: ansys/actions/_setup-python@main
      with:
        python-version: ${{ inputs.python-version }}
        use-cache: ${{ inputs.use-python-cache }}

    - name: "Install pre-commit"
      shell: bash
      run: |
        python -m pip install --upgrade pip pre-commit
        pre-commit install

    - name: "Run pre-commit"
      shell: bash
      run: pre-commit run --all-files --show-diff-on-failure

    - name: Check docker directory existence
      id: checkdocker
      run: |
        if [ -d "./docker" ]; then
          echo "::set-output name=exists::true"
        fi

    - name: Run Dockerfile linting
      uses: ansys/actions/docker-style
      if: steps.checkdocker.outputs.exists == 'true'
      with:
        working_directory: ${{ inputs.docker-directory }}
        recursive: ${{ inputs.docker-recursive }}
