name: >
  Tests pytest action

description: >
  Run a test suite using `the pytest framework
  <https://docs.pytest.org/en/stable/>`_.

inputs:

  # Optional inputs
  python-version:
    description: >
      Python version used for installing and running ``pytest``.
    default: '3.10'
    required: false
    type: string

  use-python-cache:
    description: >
      Whether to use the Python cache for installing previously downloaded
      libraries. If ``true``, previously downloaded libraries are installed form the
      Python cache. If ``false``, libraries are downloaded from the PyPI index.
    required: false
    default: true
    type: boolean

  pytest-markers:
    description: >
      Set of `pytest markers
      <https://docs.pytest.org/en/stable/example/markers.html>`_ in the form of
      a string. These markers are used to discretize tests when running the test
      session.
    default: ''
    required: false
    type: string

  pytest-extra-args:
    description: >
      Set of additional ``pytest`` arguments in the form of a string.
    default: ''
    required: false

  pytest-postargs:
    description: >
      Directory of the test suite and the level of verbosity.
    default: 'tests -vv'
    required: false
    type: string

  requires-xvfb:
    description: >
      If ``true``, installs `X Virtual Frame Buffer (XVFB)
      <https://www.x.org/releases/X11R7.6/doc/man/man1/Xvfb.1.xhtml>`_ and
      runs the whole test session using XVFB. The default is ``false``.
    default: false
    required: false
    type: boolean

  checkout:
    description: >
      If ``true``, clones the repository in the CI/CD machine. Use ``false``
      when not using this action as complete job need to.
    default: true
    required: false
    type: boolean


runs:
  using: "composite"
  steps:
  
    - name: "Install Git and clone project"
      uses: actions/checkout@v3
      if: ${{ inputs.checkout == 'true' }}
  
    - name: "Set up Python"
      uses: pyansys/actions/_setup-python@main
      with:
        python-version: ${{ inputs.python-version }}
        use-cache: ${{ inputs.use-python-cache }}

    - name: "Update pip"
      shell: bash
      run: python -m pip install -U pip
  
    - name: "Install Python library"
      shell: bash
      run: python -m pip install .

    - name: "Install X Virtual Frame Buffer"
      shell: bash
      if: inputs.requires-xvfb == 'true'
      run: |
        sudo apt-get install xvfb

    - name: "Check if requirements.txt file exists"
      shell: bash
      run: |
        echo "EXISTS_TESTS_REQUIREMENTS=$(if [ -f requirements/requirements_tests.txt ]; then echo 'true'; else echo 'false'; fi)" >> $GITHUB_ENV

    - name: "Print previous output"
      shell: bash
      run:
        echo "Output was found ${{ env.EXISTS_TESTS_REQUIREMENTS }}"

    - name: "Install test dependencies from the requirements file"
      shell: bash
      if: env.EXISTS_TESTS_REQUIREMENTS == 'true'
      run: python -m pip install -r requirements/requirements_tests.txt

    - name: "Install test dependencies from pyproject.toml"
      shell: bash
      if: env.EXISTS_TESTS_REQUIREMENTS == 'false'
      run: python -m pip install .[tests]
    
    - name: "Executing test suite without using xvfb"
      if: inputs.requires-xvfb == 'false'
      shell: bash
      run: |
        pytest ${{ inputs.pytest-markers }} ${{ inputs.pytest-extra-args }} ${{ inputs.pytest-postargs }}

    - name: "Executing test suite using xvfb"
      if: inputs.requires-xvfb == 'true'
      shell: bash
      run: |
        xvfb-run pytest ${{ inputs.pytest-markers }} ${{ inputs.pytest-extra-args }} ${{ inputs.pytest-postargs }}
