name: release
on:
  push:
    tags:
      - "v*.*.*"

env:
  MAIN_PYTHON_VERSION: '3.12'
  DOCUMENTATION_CNAME: 'actions.docs.ansys.com'
  LIBRARY_NAME: 'ansys-actions-flit'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:

  changelog-deployment:
    name: "Changelog"
    permissions:
      contents: write # Needed to create PR for changelog
      pull-requests: write # Needed to create PR for changelog
    runs-on: ubuntu-latest
    steps:
      - uses: ansys/actions/doc-deploy-changelog@main
        with:
          token: ${{ secrets.PYANSYS_CI_BOT_TOKEN }}
          bot-user: ${{ secrets.PYANSYS_CI_BOT_USERNAME }}
          bot-email: ${{ secrets.PYANSYS_CI_BOT_EMAIL }}

  code-style:
    name: "Code style"
    runs-on: ubuntu-latest
    steps:
      - uses: ansys/actions/code-style@main
        with:
          python-version: ${{ env.MAIN_PYTHON_VERSION }}
          use-python-cache: false

  doc-style:
    name: "Doc style"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: ansys/actions/doc-style@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  doc-build:
    name: "Doc build"
    runs-on: ubuntu-latest
    needs: doc-style
    steps:
      - uses: ansys/actions/doc-build@main
        with:
          group-dependencies-name: 'doc'
          needs-quarto: true
          python-version: ${{ env.MAIN_PYTHON_VERSION }}
          skip-install: true
          use-python-cache: false

  tests:
    name: "Tests"
    runs-on: ubuntu-latest
    needs: code-style
    permissions:
      contents: read
    steps:

    - name: "Install Git and clone project"
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false

    - name: "Set up Python"
      uses: ansys/actions/_setup-python@main
      with:
        python-version: ${{ env.MAIN_PYTHON_VERSION }}
        use-cache: false
        provision-uv: false
        prune-uv-cache: false

    - name: "Install build and twine"
      shell: bash
      run: |
        python -m pip install build twine

    - name: "Build distribution artifacts and check their health"
      shell: bash
      run: |
        python -m build .ci/${LIBRARY_NAME}
        ls -R .ci/${LIBRARY_NAME}/dist
        python -m twine check .ci/${LIBRARY_NAME}/dist/**

    - name: "Upload distribution artifacts"
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: ${{ env.LIBRARY_NAME }}-artifacts
        path: .ci/${{ env.LIBRARY_NAME }}/dist
        retention-days: 7

  release:
    name: "Release"
    runs-on: ubuntu-latest
    needs: [doc-build, tests]
    env:
        MAJOR: ${{ needs.rolling-release.outputs.tag_major }}
    permissions:
      id-token: write # Needed for trusted publishing OIDC
      contents: write # Needed for releasing to GitHub
    steps:

    - name: "Download distribution artifacts"
      uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
      with:
        name: ${{ env.LIBRARY_NAME }}-artifacts
        path: dist

    - name: "Download HTML documentation"
      uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
      with:
        name: documentation-html
        path: documentation-html

    - name: "Zip HTML documentation"
      uses: vimtor/action-zip@5407800dfb2b1b37d48df912330cb22f4ab6f422 # v1.3
      with:
        files: documentation-html
        dest: documentation-html.zip

    - name: "Download PDF documentation"
      uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
      with:
        name: documentation-pdf
        path: documentation-pdf

    - name: "Zip PDF documentation"
      uses: vimtor/action-zip@5407800dfb2b1b37d48df912330cb22f4ab6f422 # v1.3
      with:
        files: documentation-pdf
        dest: documentation-pdf.zip

    - name: "Display the structure of downloaded files"
      shell: bash
      run: ls -R

    - name: "Upload artifacts to test PyPI using trusted publisher"
      uses: pypa/gh-action-pypi-publish@dc37677b2e1c63e2034f94d8a5b11f265b73ba33 # v1.14.2
      with:
        repository-url: "https://test.pypi.org/legacy/"
        print-hash: true
        skip-existing: false
        verbose: true

    - name: "Generate link to migration guide for current release"
      id: link-migration-guide
      run: |
        BASE_LINK="https://actions.docs.ansys.com/version/stable/migrations/index.html#version-v"
        # Append version number to point to specific entry in the migration guide
        LINK="${BASE_LINK}${MAJOR}"
        echo "LINK=${LINK}" >> $GITHUB_OUTPUT

    - name: "Release to GitHub"
      uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # v3.0.2
      with:
        body: >
          If you are migrating the actions of your project to a new major release, breaking changes can be expected.

          To make sure everything is compatible with your current workflow, refer to the
          [Migration Guide for v${{ env.MAJOR }}](${{ steps.link-migration-guide.outputs.LINK }}) to find out more
          about new features and potential breaking changes.
        generate_release_notes: true
        files: |
          documentation-html.zip
          documentation-pdf.zip

  doc-deploy-stable:
    name: "Deploy stable documentation"
    runs-on: ubuntu-latest
    needs: release
    permissions:
      contents: write # Needed to update files on the gh-pages branch
    steps:
      - uses: ansys/actions/doc-deploy-stable@main
        with:
          cname: ${{ env.DOCUMENTATION_CNAME }}
          token: ${{ secrets.GITHUB_TOKEN }}
          bot-user: ${{ secrets.PYANSYS_CI_BOT_USERNAME }}
          bot-email: ${{ secrets.PYANSYS_CI_BOT_EMAIL }}
